config som_system_altera_mm_interconnect_180_nzcyb6q_cfg;
		design som_system_altera_mm_interconnect_180_nzcyb6q;
		instance som_system_altera_mm_interconnect_180_nzcyb6q.mm_clock_crossing_bridge_0_m0_translator use som_system_altera_merlin_master_translator_180.altera_merlin_master_translator;
		instance som_system_altera_mm_interconnect_180_nzcyb6q.emif_0_ctrl_amm_0_translator use som_system_altera_merlin_slave_translator_180.altera_merlin_slave_translator;
endconfig

