config som_system_altera_mm_interconnect_180_d4sniia_cfg;
		design som_system_altera_mm_interconnect_180_d4sniia;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_translator use som_system_altera_merlin_slave_translator_180.altera_merlin_slave_translator;
		instance som_system_altera_mm_interconnect_180_d4sniia.mux_ddr_0_altera_axi_master_agent use som_system_altera_merlin_axi_master_ni_180.altera_merlin_axi_master_ni;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_agent use som_system_altera_merlin_slave_agent_180.altera_merlin_slave_agent;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_agent_rsp_fifo use som_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_agent_rdata_fifo use som_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance som_system_altera_mm_interconnect_180_d4sniia.router use som_system_altera_merlin_router_180.som_system_altera_merlin_router_180_gil3sua;
		instance som_system_altera_mm_interconnect_180_d4sniia.router_001 use som_system_altera_merlin_router_180.som_system_altera_merlin_router_180_gil3sua;
		instance som_system_altera_mm_interconnect_180_d4sniia.router_002 use som_system_altera_merlin_router_180.som_system_altera_merlin_router_180_jxs3q3q;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_burst_adapter use som_system_altera_merlin_burst_adapter_180.altera_merlin_burst_adapter;
		instance som_system_altera_mm_interconnect_180_d4sniia.cmd_demux use som_system_altera_merlin_demultiplexer_180.som_system_altera_merlin_demultiplexer_180_reioipy;
		instance som_system_altera_mm_interconnect_180_d4sniia.cmd_demux_001 use som_system_altera_merlin_demultiplexer_180.som_system_altera_merlin_demultiplexer_180_reioipy;
		instance som_system_altera_mm_interconnect_180_d4sniia.cmd_mux use som_system_altera_merlin_multiplexer_180.som_system_altera_merlin_multiplexer_180_xdoo6gq;
		instance som_system_altera_mm_interconnect_180_d4sniia.rsp_demux use som_system_altera_merlin_demultiplexer_180.som_system_altera_merlin_demultiplexer_180_ae2iwoi;
		instance som_system_altera_mm_interconnect_180_d4sniia.rsp_mux use som_system_altera_merlin_multiplexer_180.som_system_altera_merlin_multiplexer_180_2q47q3i;
		instance som_system_altera_mm_interconnect_180_d4sniia.rsp_mux_001 use som_system_altera_merlin_multiplexer_180.som_system_altera_merlin_multiplexer_180_2q47q3i;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_rsp_width_adapter use som_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance som_system_altera_mm_interconnect_180_d4sniia.mm_clock_crossing_bridge_0_s0_cmd_width_adapter use som_system_altera_merlin_width_adapter_180.altera_merlin_width_adapter;
		instance som_system_altera_mm_interconnect_180_d4sniia.crosser use som_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance som_system_altera_mm_interconnect_180_d4sniia.crosser_001 use som_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance som_system_altera_mm_interconnect_180_d4sniia.crosser_002 use som_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance som_system_altera_mm_interconnect_180_d4sniia.crosser_003 use som_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance som_system_altera_mm_interconnect_180_d4sniia.avalon_st_adapter use som_system_altera_avalon_st_adapter_180.som_system_altera_avalon_st_adapter_180_v3lgypq;
endconfig

