config som_system_altera_avalon_st_adapter_180_bbxpcfy_cfg;
		design som_system_altera_avalon_st_adapter_180_bbxpcfy;
		instance som_system_altera_avalon_st_adapter_180_bbxpcfy.channel_adapter_0 use som_system_channel_adapter_180.som_system_channel_adapter_180_agpsntq;
endconfig

