config som_system_altera_avalon_st_adapter_180_caevfly_cfg;
		design som_system_altera_avalon_st_adapter_180_caevfly;
		instance som_system_altera_avalon_st_adapter_180_caevfly.error_adapter_0 use som_system_error_adapter_180.som_system_error_adapter_180_ww4pkiq;
endconfig

