-- soc_system_codec_clocks_10_ns6zpna.vhd

-- Generated using ACDS version 18.0 614

library IEEE;
library soc_system_altera_iopll_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use soc_system_altera_iopll_180.soc_system_codec_clocks_10_ns6zpna_pkg.all;

entity soc_system_codec_clocks_10_ns6zpna is
	port (
		ad1939_abclk_in_clk   : in  std_logic := '0'; --   ad1939_abclk_in.clk
		ad1939_abclk_out_clk  : out std_logic;        --  ad1939_abclk_out.clk
		ad1939_alrclk_in_clk  : in  std_logic := '0'; --  ad1939_alrclk_in.clk
		ad1939_alrclk_out_clk : out std_logic;        -- ad1939_alrclk_out.clk
		ad1939_mclk_in_clk    : in  std_logic := '0'; --    ad1939_mclk_in.clk
		ad1939_mclk_out_clk   : out std_logic;        --   ad1939_mclk_out.clk
		reset_in_reset        : in  std_logic := '0'; --          reset_in.reset
		reset_out_reset       : out std_logic;        --         reset_out.reset
		sys_clk_clk           : out std_logic         --           sys_clk.clk
	);
end entity soc_system_codec_clocks_10_ns6zpna;

architecture rtl of soc_system_codec_clocks_10_ns6zpna is
begin

	mclk_pll : component soc_system_altera_iopll_180.soc_system_codec_clocks_10_ns6zpna_pkg.soc_system_altera_iopll_180_nrxle5y
		port map (
			rst      => reset_in_reset,     --   reset.reset
			refclk   => ad1939_mclk_in_clk, --  refclk.clk
			outclk_0 => sys_clk_clk         -- outclk0.clk
		);

	ad1939_abclk_out_clk <= ad1939_abclk_in_clk;

	ad1939_alrclk_out_clk <= ad1939_alrclk_in_clk;

	ad1939_mclk_out_clk <= ad1939_mclk_in_clk;

	reset_out_reset <= reset_in_reset;

end architecture rtl; -- of soc_system_codec_clocks_10_ns6zpna
