config soc_system_altera_jtag_avalon_master_180_sb3msya_cfg;
		design soc_system_altera_jtag_avalon_master_180_sb3msya;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.jtag_phy_embedded_in_jtag_master use soc_system_altera_jtag_dc_streaming_180.altera_avalon_st_jtag_interface;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.timing_adt use soc_system_timing_adapter_180.soc_system_timing_adapter_180_sw6zsri;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.fifo use soc_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.b2p use soc_system_altera_avalon_st_bytes_to_packets_180.altera_avalon_st_bytes_to_packets;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.p2b use soc_system_altera_avalon_st_packets_to_bytes_180.altera_avalon_st_packets_to_bytes;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.transacto use soc_system_altera_avalon_packets_to_master_180.altera_avalon_packets_to_master;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.b2p_adapter use soc_system_channel_adapter_180.soc_system_channel_adapter_180_6j26mga;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.p2b_adapter use soc_system_channel_adapter_180.soc_system_channel_adapter_180_77yxgci;
		instance soc_system_altera_jtag_avalon_master_180_sb3msya.rst_controller use soc_system_altera_reset_controller_180.altera_reset_controller;
endconfig

