config som_system_altera_emif_cal_slave_nf_180_5pbk77i_cfg;
		design som_system_altera_emif_cal_slave_nf_180_5pbk77i;
		instance som_system_altera_emif_cal_slave_nf_180_5pbk77i.ioaux_master_bridge use som_system_altera_avalon_mm_bridge_180.altera_avalon_mm_bridge;
		instance som_system_altera_emif_cal_slave_nf_180_5pbk77i.ioaux_soft_ram use som_system_altera_avalon_onchip_memory2_180.som_system_altera_avalon_onchip_memory2_180_m2wik5y;
		instance som_system_altera_emif_cal_slave_nf_180_5pbk77i.mm_interconnect_0 use som_system_altera_mm_interconnect_180.som_system_altera_mm_interconnect_180_l5dmrei;
		instance som_system_altera_emif_cal_slave_nf_180_5pbk77i.rst_controller use som_system_altera_reset_controller_180.altera_reset_controller;
endconfig

