config soc_system_altera_mm_interconnect_180_iy27qwy_cfg;
		design soc_system_altera_mm_interconnect_180_iy27qwy;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.jtag_master_master_translator use soc_system_altera_merlin_master_translator_180.altera_merlin_master_translator;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.mic_array_0_s1_translator use soc_system_altera_merlin_slave_translator_180.altera_merlin_slave_translator;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.jtag_master_master_agent use soc_system_altera_merlin_master_agent_180.altera_merlin_master_agent;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.mic_array_0_s1_agent use soc_system_altera_merlin_slave_agent_180.altera_merlin_slave_agent;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.mic_array_0_s1_agent_rsp_fifo use soc_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.mic_array_0_s1_agent_rdata_fifo use soc_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.router use soc_system_altera_merlin_router_180.soc_system_altera_merlin_router_180_4qn3tqa;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.router_001 use soc_system_altera_merlin_router_180.soc_system_altera_merlin_router_180_nl6zyvy;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.cmd_demux use soc_system_altera_merlin_demultiplexer_180.soc_system_altera_merlin_demultiplexer_180_jh7dbka;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.cmd_mux use soc_system_altera_merlin_multiplexer_180.soc_system_altera_merlin_multiplexer_180_yp3ydli;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.rsp_demux use soc_system_altera_merlin_demultiplexer_180.soc_system_altera_merlin_demultiplexer_180_ezafeci;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.rsp_mux use soc_system_altera_merlin_multiplexer_180.soc_system_altera_merlin_multiplexer_180_sthvrba;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.crosser use soc_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.crosser_001 use soc_system_altera_avalon_st_handshake_clock_crosser_180.altera_avalon_st_handshake_clock_crosser;
		instance soc_system_altera_mm_interconnect_180_iy27qwy.avalon_st_adapter use soc_system_altera_avalon_st_adapter_180.soc_system_altera_avalon_st_adapter_180_7g3x3ri;
endconfig

