-- soc_system.vhd

-- Generated using ACDS version 18.0 614

library IEEE;
library soc_system_FE_Qsys_AD1939_Audio_Research_v1_10;
library soc_system_codec_clocks_10;
library soc_system_altera_emif_a10_hps_180;
library soc_system_delay_and_sum_beamformer_10;
library soc_system_altera_arria10_hps_180;
library soc_system_altera_jtag_avalon_master_180;
library soc_system_mic_array_10;
library soc_system_mic_array_clocks_10;
library soc_system_mono2stereo_adapter_10;
library soc_system_altera_avalon_sysid_qsys_180;
library soc_system_altera_mm_interconnect_180;
library soc_system_altera_avalon_st_adapter_180;
library soc_system_altera_reset_controller_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use soc_system_FE_Qsys_AD1939_Audio_Research_v1_10.soc_system_pkg.all;
use soc_system_codec_clocks_10.soc_system_pkg.all;
use soc_system_altera_emif_a10_hps_180.soc_system_pkg.all;
use soc_system_delay_and_sum_beamformer_10.soc_system_pkg.all;
use soc_system_altera_arria10_hps_180.soc_system_pkg.all;
use soc_system_altera_jtag_avalon_master_180.soc_system_pkg.all;
use soc_system_mic_array_10.soc_system_pkg.all;
use soc_system_mic_array_clocks_10.soc_system_pkg.all;
use soc_system_mono2stereo_adapter_10.soc_system_pkg.all;
use soc_system_altera_avalon_sysid_qsys_180.soc_system_pkg.all;
use soc_system_altera_mm_interconnect_180.soc_system_pkg.all;
use soc_system_altera_avalon_st_adapter_180.soc_system_pkg.all;
use soc_system_altera_reset_controller_180.soc_system_pkg.all;

entity soc_system is
	port (
		ad1939_abclk_clk                     : in    std_logic                     := '0';             --                 ad1939_abclk.clk
		ad1939_alrclk_clk                    : in    std_logic                     := '0';             --                ad1939_alrclk.clk
		ad1939_mclk_clk                      : in    std_logic                     := '0';             --                  ad1939_mclk.clk
		ad1939_physical_ad1939_adc_asdata1   : in    std_logic                     := '0';             --              ad1939_physical.ad1939_adc_asdata1
		ad1939_physical_ad1939_adc_asdata2   : in    std_logic                     := '0';             --                             .ad1939_adc_asdata2
		ad1939_physical_ad1939_dac_dbclk     : out   std_logic;                                        --                             .ad1939_dac_dbclk
		ad1939_physical_ad1939_dac_dlrclk    : out   std_logic;                                        --                             .ad1939_dac_dlrclk
		ad1939_physical_ad1939_dac_dsdata1   : out   std_logic;                                        --                             .ad1939_dac_dsdata1
		ad1939_physical_ad1939_dac_dsdata2   : out   std_logic;                                        --                             .ad1939_dac_dsdata2
		ad1939_physical_ad1939_dac_dsdata3   : out   std_logic;                                        --                             .ad1939_dac_dsdata3
		ad1939_physical_ad1939_dac_dsdata4   : out   std_logic;                                        --                             .ad1939_dac_dsdata4
		ddr4_global_reset_reset_sink_reset_n : in    std_logic                     := '0';             -- ddr4_global_reset_reset_sink.reset_n
		ddr4_mem_conduit_end_mem_ck          : out   std_logic_vector(0 downto 0);                     --         ddr4_mem_conduit_end.mem_ck
		ddr4_mem_conduit_end_mem_ck_n        : out   std_logic_vector(0 downto 0);                     --                             .mem_ck_n
		ddr4_mem_conduit_end_mem_a           : out   std_logic_vector(16 downto 0);                    --                             .mem_a
		ddr4_mem_conduit_end_mem_act_n       : out   std_logic_vector(0 downto 0);                     --                             .mem_act_n
		ddr4_mem_conduit_end_mem_ba          : out   std_logic_vector(1 downto 0);                     --                             .mem_ba
		ddr4_mem_conduit_end_mem_bg          : out   std_logic_vector(1 downto 0);                     --                             .mem_bg
		ddr4_mem_conduit_end_mem_cke         : out   std_logic_vector(0 downto 0);                     --                             .mem_cke
		ddr4_mem_conduit_end_mem_cs_n        : out   std_logic_vector(0 downto 0);                     --                             .mem_cs_n
		ddr4_mem_conduit_end_mem_odt         : out   std_logic_vector(0 downto 0);                     --                             .mem_odt
		ddr4_mem_conduit_end_mem_reset_n     : out   std_logic_vector(0 downto 0);                     --                             .mem_reset_n
		ddr4_mem_conduit_end_mem_par         : out   std_logic_vector(0 downto 0);                     --                             .mem_par
		ddr4_mem_conduit_end_mem_alert_n     : in    std_logic_vector(0 downto 0)  := (others => '0'); --                             .mem_alert_n
		ddr4_mem_conduit_end_mem_dqs         : inout std_logic_vector(3 downto 0)  := (others => '0'); --                             .mem_dqs
		ddr4_mem_conduit_end_mem_dqs_n       : inout std_logic_vector(3 downto 0)  := (others => '0'); --                             .mem_dqs_n
		ddr4_mem_conduit_end_mem_dq          : inout std_logic_vector(31 downto 0) := (others => '0'); --                             .mem_dq
		ddr4_mem_conduit_end_mem_dbi_n       : inout std_logic_vector(3 downto 0)  := (others => '0'); --                             .mem_dbi_n
		ddr4_oct_conduit_end_oct_rzqin       : in    std_logic                     := '0';             --         ddr4_oct_conduit_end.oct_rzqin
		ddr4_pll_ref_clk_clock_sink_clk      : in    std_logic                     := '0';             --  ddr4_pll_ref_clk_clock_sink.clk
		hps_f2h_cold_reset_req_reset_n       : in    std_logic                     := '0';             --       hps_f2h_cold_reset_req.reset_n
		hps_f2h_irq0_irq                     : in    std_logic_vector(31 downto 0) := (others => '0'); --                 hps_f2h_irq0.irq
		hps_f2h_irq1_irq                     : in    std_logic_vector(31 downto 0) := (others => '0'); --                 hps_f2h_irq1.irq
		hps_f2h_warm_reset_req_reset_n       : in    std_logic                     := '0';             --       hps_f2h_warm_reset_req.reset_n
		hps_i2c0_sda_i                       : in    std_logic                     := '0';             --                     hps_i2c0.sda_i
		hps_i2c0_sda_oe                      : out   std_logic;                                        --                             .sda_oe
		hps_i2c0_clk_clk                     : out   std_logic;                                        --                 hps_i2c0_clk.clk
		hps_i2c0_scl_in_clk                  : in    std_logic                     := '0';             --              hps_i2c0_scl_in.clk
		hps_io_hps_io_phery_emac1_TX_CLK     : out   std_logic;                                        --                       hps_io.hps_io_phery_emac1_TX_CLK
		hps_io_hps_io_phery_emac1_TXD0       : out   std_logic;                                        --                             .hps_io_phery_emac1_TXD0
		hps_io_hps_io_phery_emac1_TXD1       : out   std_logic;                                        --                             .hps_io_phery_emac1_TXD1
		hps_io_hps_io_phery_emac1_TXD2       : out   std_logic;                                        --                             .hps_io_phery_emac1_TXD2
		hps_io_hps_io_phery_emac1_TXD3       : out   std_logic;                                        --                             .hps_io_phery_emac1_TXD3
		hps_io_hps_io_phery_emac1_RX_CTL     : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RX_CTL
		hps_io_hps_io_phery_emac1_TX_CTL     : out   std_logic;                                        --                             .hps_io_phery_emac1_TX_CTL
		hps_io_hps_io_phery_emac1_RX_CLK     : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RX_CLK
		hps_io_hps_io_phery_emac1_RXD0       : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RXD0
		hps_io_hps_io_phery_emac1_RXD1       : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RXD1
		hps_io_hps_io_phery_emac1_RXD2       : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RXD2
		hps_io_hps_io_phery_emac1_RXD3       : in    std_logic                     := '0';             --                             .hps_io_phery_emac1_RXD3
		hps_io_hps_io_phery_emac1_MDIO       : inout std_logic                     := '0';             --                             .hps_io_phery_emac1_MDIO
		hps_io_hps_io_phery_emac1_MDC        : out   std_logic;                                        --                             .hps_io_phery_emac1_MDC
		hps_io_hps_io_phery_emac2_TX_CLK     : out   std_logic;                                        --                             .hps_io_phery_emac2_TX_CLK
		hps_io_hps_io_phery_emac2_TXD0       : out   std_logic;                                        --                             .hps_io_phery_emac2_TXD0
		hps_io_hps_io_phery_emac2_TXD1       : out   std_logic;                                        --                             .hps_io_phery_emac2_TXD1
		hps_io_hps_io_phery_emac2_TXD2       : out   std_logic;                                        --                             .hps_io_phery_emac2_TXD2
		hps_io_hps_io_phery_emac2_TXD3       : out   std_logic;                                        --                             .hps_io_phery_emac2_TXD3
		hps_io_hps_io_phery_emac2_RX_CTL     : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RX_CTL
		hps_io_hps_io_phery_emac2_TX_CTL     : out   std_logic;                                        --                             .hps_io_phery_emac2_TX_CTL
		hps_io_hps_io_phery_emac2_RX_CLK     : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RX_CLK
		hps_io_hps_io_phery_emac2_RXD0       : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RXD0
		hps_io_hps_io_phery_emac2_RXD1       : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RXD1
		hps_io_hps_io_phery_emac2_RXD2       : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RXD2
		hps_io_hps_io_phery_emac2_RXD3       : in    std_logic                     := '0';             --                             .hps_io_phery_emac2_RXD3
		hps_io_hps_io_phery_emac2_MDIO       : inout std_logic                     := '0';             --                             .hps_io_phery_emac2_MDIO
		hps_io_hps_io_phery_emac2_MDC        : out   std_logic;                                        --                             .hps_io_phery_emac2_MDC
		hps_io_hps_io_phery_sdmmc_CMD        : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_CMD
		hps_io_hps_io_phery_sdmmc_D0         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D0
		hps_io_hps_io_phery_sdmmc_D1         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D1
		hps_io_hps_io_phery_sdmmc_D2         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D2
		hps_io_hps_io_phery_sdmmc_D3         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D3
		hps_io_hps_io_phery_sdmmc_D4         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D4
		hps_io_hps_io_phery_sdmmc_D5         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D5
		hps_io_hps_io_phery_sdmmc_D6         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D6
		hps_io_hps_io_phery_sdmmc_D7         : inout std_logic                     := '0';             --                             .hps_io_phery_sdmmc_D7
		hps_io_hps_io_phery_sdmmc_CCLK       : out   std_logic;                                        --                             .hps_io_phery_sdmmc_CCLK
		hps_io_hps_io_phery_usb1_DATA0       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA0
		hps_io_hps_io_phery_usb1_DATA1       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA1
		hps_io_hps_io_phery_usb1_DATA2       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA2
		hps_io_hps_io_phery_usb1_DATA3       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA3
		hps_io_hps_io_phery_usb1_DATA4       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA4
		hps_io_hps_io_phery_usb1_DATA5       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA5
		hps_io_hps_io_phery_usb1_DATA6       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA6
		hps_io_hps_io_phery_usb1_DATA7       : inout std_logic                     := '0';             --                             .hps_io_phery_usb1_DATA7
		hps_io_hps_io_phery_usb1_CLK         : in    std_logic                     := '0';             --                             .hps_io_phery_usb1_CLK
		hps_io_hps_io_phery_usb1_STP         : out   std_logic;                                        --                             .hps_io_phery_usb1_STP
		hps_io_hps_io_phery_usb1_DIR         : in    std_logic                     := '0';             --                             .hps_io_phery_usb1_DIR
		hps_io_hps_io_phery_usb1_NXT         : in    std_logic                     := '0';             --                             .hps_io_phery_usb1_NXT
		hps_io_hps_io_phery_uart0_RX         : in    std_logic                     := '0';             --                             .hps_io_phery_uart0_RX
		hps_io_hps_io_phery_uart0_TX         : out   std_logic;                                        --                             .hps_io_phery_uart0_TX
		hps_io_hps_io_phery_uart0_CTS_N      : in    std_logic                     := '0';             --                             .hps_io_phery_uart0_CTS_N
		hps_io_hps_io_phery_uart0_RTS_N      : out   std_logic;                                        --                             .hps_io_phery_uart0_RTS_N
		hps_spim1_mosi_o                     : out   std_logic;                                        --                    hps_spim1.mosi_o
		hps_spim1_miso_i                     : in    std_logic                     := '0';             --                             .miso_i
		hps_spim1_ss_in_n                    : in    std_logic                     := '0';             --                             .ss_in_n
		hps_spim1_mosi_oe                    : out   std_logic;                                        --                             .mosi_oe
		hps_spim1_ss0_n_o                    : out   std_logic;                                        --                             .ss0_n_o
		hps_spim1_ss1_n_o                    : out   std_logic;                                        --                             .ss1_n_o
		hps_spim1_ss2_n_o                    : out   std_logic;                                        --                             .ss2_n_o
		hps_spim1_ss3_n_o                    : out   std_logic;                                        --                             .ss3_n_o
		hps_spim1_sclk_out_clk               : out   std_logic;                                        --           hps_spim1_sclk_out.clk
		mic_array_0_led_sd                   : out   std_logic;                                        --                  mic_array_0.led_sd
		mic_array_0_led_ws                   : out   std_logic;                                        --                             .led_ws
		mic_array_0_sd                       : in    std_logic                     := '0';             --                             .sd
		mic_array_0_ws                       : out   std_logic;                                        --                             .ws
		mic_array_sck_clk                    : out   std_logic;                                        --                mic_array_sck.clk
		reset_reset                          : in    std_logic                     := '0'              --                        reset.reset
	);
end entity soc_system;

architecture rtl of soc_system is
	signal codec_clocks_ad1939_abclk_out_clk                                   : std_logic;                       -- codec_clocks:ad1939_abclk_out_clk -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_ADC_ABCLK
	signal codec_clocks_ad1939_alrclk_out_clk                                  : std_logic;                       -- codec_clocks:ad1939_alrclk_out_clk -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_ADC_ALRCLK
	signal codec_clocks_ad1939_mclk_out_clk                                    : std_logic;                       -- codec_clocks:ad1939_mclk_out_clk -> mic_array_clocks:ad1939_mclk_clk
	signal mic_array_clocks_sck_master_clk                                     : std_logic;                       -- mic_array_clocks:sck_master_clk -> [mic_array_0:sck_master, mm_interconnect_0:mic_array_clocks_sck_master_clk, rst_controller:clk]
	signal mic_array_clocks_sck_rcv_ch0_clk                                    : std_logic;                       -- mic_array_clocks:sck_rcv_ch0_clk -> mic_array_0:sck_rcv
	signal codec_clocks_sys_clk_clk                                            : std_logic;                       -- codec_clocks:sys_clk_clk -> [FE_Qsys_AD1939_Audio_Research_v1_0:sys_clk, avalon_st_adapter:in_clk_0_clk, avalon_st_adapter_001:in_clk_0_clk, avalon_st_adapter_002:in_clk_0_clk, delay_and_sum_beamformer_0:clk, hps:h2f_lw_axi_clk, jtag_master:clk_clk, mic_array_0:sys_clk, mm_interconnect_0:codec_clocks_sys_clk_clk, mono2stereo_adapter_0:clk, sysid_qsys_0:clock]
	signal hps_emif_gp_to_emif                                                 : std_logic_vector(1 downto 0);    -- hps:emif_gp_to_emif -> ddr4:hps_to_emif_gp
	signal ddr4_hps_emif_conduit_end_emif_to_hps                               : std_logic_vector(4095 downto 0); -- ddr4:emif_to_hps -> hps:emif_emif_to_hps
	signal ddr4_hps_emif_conduit_end_emif_to_gp                                : std_logic_vector(0 downto 0);    -- ddr4:emif_to_hps_gp -> hps:emif_emif_to_gp
	signal hps_emif_hps_to_emif                                                : std_logic_vector(4095 downto 0); -- hps:emif_hps_to_emif -> ddr4:hps_to_emif
	signal codec_clocks_reset_out_reset                                        : std_logic;                       -- codec_clocks:reset_out_reset -> [FE_Qsys_AD1939_Audio_Research_v1_0:sys_reset, avalon_st_adapter:in_rst_0_reset, avalon_st_adapter_001:in_rst_0_reset, avalon_st_adapter_002:in_rst_0_reset, codec_clocks_reset_out_reset:in, delay_and_sum_beamformer_0:reset, jtag_master:clk_reset_reset, mic_array_0:rst, mm_interconnect_0:hps_h2f_lw_axi_reset_reset_bridge_in_reset_reset, mm_interconnect_0:jtag_master_clk_reset_reset_bridge_in_reset_reset, mono2stereo_adapter_0:rst, rst_controller:reset_in0]
	signal hps_h2f_lw_axi_master_awburst                                       : std_logic_vector(1 downto 0);    -- hps:h2f_lw_AWBURST -> mm_interconnect_0:hps_h2f_lw_axi_master_awburst
	signal hps_h2f_lw_axi_master_awuser                                        : std_logic_vector(4 downto 0);    -- hps:h2f_lw_AWUSER -> mm_interconnect_0:hps_h2f_lw_axi_master_awuser
	signal hps_h2f_lw_axi_master_arlen                                         : std_logic_vector(3 downto 0);    -- hps:h2f_lw_ARLEN -> mm_interconnect_0:hps_h2f_lw_axi_master_arlen
	signal hps_h2f_lw_axi_master_wstrb                                         : std_logic_vector(3 downto 0);    -- hps:h2f_lw_WSTRB -> mm_interconnect_0:hps_h2f_lw_axi_master_wstrb
	signal hps_h2f_lw_axi_master_wready                                        : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_wready -> hps:h2f_lw_WREADY
	signal hps_h2f_lw_axi_master_rid                                           : std_logic_vector(3 downto 0);    -- mm_interconnect_0:hps_h2f_lw_axi_master_rid -> hps:h2f_lw_RID
	signal hps_h2f_lw_axi_master_rready                                        : std_logic;                       -- hps:h2f_lw_RREADY -> mm_interconnect_0:hps_h2f_lw_axi_master_rready
	signal hps_h2f_lw_axi_master_awlen                                         : std_logic_vector(3 downto 0);    -- hps:h2f_lw_AWLEN -> mm_interconnect_0:hps_h2f_lw_axi_master_awlen
	signal hps_h2f_lw_axi_master_wid                                           : std_logic_vector(3 downto 0);    -- hps:h2f_lw_WID -> mm_interconnect_0:hps_h2f_lw_axi_master_wid
	signal hps_h2f_lw_axi_master_arcache                                       : std_logic_vector(3 downto 0);    -- hps:h2f_lw_ARCACHE -> mm_interconnect_0:hps_h2f_lw_axi_master_arcache
	signal hps_h2f_lw_axi_master_wvalid                                        : std_logic;                       -- hps:h2f_lw_WVALID -> mm_interconnect_0:hps_h2f_lw_axi_master_wvalid
	signal hps_h2f_lw_axi_master_araddr                                        : std_logic_vector(20 downto 0);   -- hps:h2f_lw_ARADDR -> mm_interconnect_0:hps_h2f_lw_axi_master_araddr
	signal hps_h2f_lw_axi_master_arprot                                        : std_logic_vector(2 downto 0);    -- hps:h2f_lw_ARPROT -> mm_interconnect_0:hps_h2f_lw_axi_master_arprot
	signal hps_h2f_lw_axi_master_awprot                                        : std_logic_vector(2 downto 0);    -- hps:h2f_lw_AWPROT -> mm_interconnect_0:hps_h2f_lw_axi_master_awprot
	signal hps_h2f_lw_axi_master_wdata                                         : std_logic_vector(31 downto 0);   -- hps:h2f_lw_WDATA -> mm_interconnect_0:hps_h2f_lw_axi_master_wdata
	signal hps_h2f_lw_axi_master_arvalid                                       : std_logic;                       -- hps:h2f_lw_ARVALID -> mm_interconnect_0:hps_h2f_lw_axi_master_arvalid
	signal hps_h2f_lw_axi_master_awcache                                       : std_logic_vector(3 downto 0);    -- hps:h2f_lw_AWCACHE -> mm_interconnect_0:hps_h2f_lw_axi_master_awcache
	signal hps_h2f_lw_axi_master_arid                                          : std_logic_vector(3 downto 0);    -- hps:h2f_lw_ARID -> mm_interconnect_0:hps_h2f_lw_axi_master_arid
	signal hps_h2f_lw_axi_master_arlock                                        : std_logic_vector(1 downto 0);    -- hps:h2f_lw_ARLOCK -> mm_interconnect_0:hps_h2f_lw_axi_master_arlock
	signal hps_h2f_lw_axi_master_awlock                                        : std_logic_vector(1 downto 0);    -- hps:h2f_lw_AWLOCK -> mm_interconnect_0:hps_h2f_lw_axi_master_awlock
	signal hps_h2f_lw_axi_master_awaddr                                        : std_logic_vector(20 downto 0);   -- hps:h2f_lw_AWADDR -> mm_interconnect_0:hps_h2f_lw_axi_master_awaddr
	signal hps_h2f_lw_axi_master_bresp                                         : std_logic_vector(1 downto 0);    -- mm_interconnect_0:hps_h2f_lw_axi_master_bresp -> hps:h2f_lw_BRESP
	signal hps_h2f_lw_axi_master_arready                                       : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_arready -> hps:h2f_lw_ARREADY
	signal hps_h2f_lw_axi_master_rdata                                         : std_logic_vector(31 downto 0);   -- mm_interconnect_0:hps_h2f_lw_axi_master_rdata -> hps:h2f_lw_RDATA
	signal hps_h2f_lw_axi_master_awready                                       : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_awready -> hps:h2f_lw_AWREADY
	signal hps_h2f_lw_axi_master_arburst                                       : std_logic_vector(1 downto 0);    -- hps:h2f_lw_ARBURST -> mm_interconnect_0:hps_h2f_lw_axi_master_arburst
	signal hps_h2f_lw_axi_master_arsize                                        : std_logic_vector(2 downto 0);    -- hps:h2f_lw_ARSIZE -> mm_interconnect_0:hps_h2f_lw_axi_master_arsize
	signal hps_h2f_lw_axi_master_bready                                        : std_logic;                       -- hps:h2f_lw_BREADY -> mm_interconnect_0:hps_h2f_lw_axi_master_bready
	signal hps_h2f_lw_axi_master_rlast                                         : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_rlast -> hps:h2f_lw_RLAST
	signal hps_h2f_lw_axi_master_wlast                                         : std_logic;                       -- hps:h2f_lw_WLAST -> mm_interconnect_0:hps_h2f_lw_axi_master_wlast
	signal hps_h2f_lw_axi_master_rresp                                         : std_logic_vector(1 downto 0);    -- mm_interconnect_0:hps_h2f_lw_axi_master_rresp -> hps:h2f_lw_RRESP
	signal hps_h2f_lw_axi_master_awid                                          : std_logic_vector(3 downto 0);    -- hps:h2f_lw_AWID -> mm_interconnect_0:hps_h2f_lw_axi_master_awid
	signal hps_h2f_lw_axi_master_bid                                           : std_logic_vector(3 downto 0);    -- mm_interconnect_0:hps_h2f_lw_axi_master_bid -> hps:h2f_lw_BID
	signal hps_h2f_lw_axi_master_bvalid                                        : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_bvalid -> hps:h2f_lw_BVALID
	signal hps_h2f_lw_axi_master_awsize                                        : std_logic_vector(2 downto 0);    -- hps:h2f_lw_AWSIZE -> mm_interconnect_0:hps_h2f_lw_axi_master_awsize
	signal hps_h2f_lw_axi_master_awvalid                                       : std_logic;                       -- hps:h2f_lw_AWVALID -> mm_interconnect_0:hps_h2f_lw_axi_master_awvalid
	signal hps_h2f_lw_axi_master_aruser                                        : std_logic_vector(4 downto 0);    -- hps:h2f_lw_ARUSER -> mm_interconnect_0:hps_h2f_lw_axi_master_aruser
	signal hps_h2f_lw_axi_master_rvalid                                        : std_logic;                       -- mm_interconnect_0:hps_h2f_lw_axi_master_rvalid -> hps:h2f_lw_RVALID
	signal jtag_master_master_readdata                                         : std_logic_vector(31 downto 0);   -- mm_interconnect_0:jtag_master_master_readdata -> jtag_master:master_readdata
	signal jtag_master_master_waitrequest                                      : std_logic;                       -- mm_interconnect_0:jtag_master_master_waitrequest -> jtag_master:master_waitrequest
	signal jtag_master_master_address                                          : std_logic_vector(31 downto 0);   -- jtag_master:master_address -> mm_interconnect_0:jtag_master_master_address
	signal jtag_master_master_read                                             : std_logic;                       -- jtag_master:master_read -> mm_interconnect_0:jtag_master_master_read
	signal jtag_master_master_byteenable                                       : std_logic_vector(3 downto 0);    -- jtag_master:master_byteenable -> mm_interconnect_0:jtag_master_master_byteenable
	signal jtag_master_master_readdatavalid                                    : std_logic;                       -- mm_interconnect_0:jtag_master_master_readdatavalid -> jtag_master:master_readdatavalid
	signal jtag_master_master_write                                            : std_logic;                       -- jtag_master:master_write -> mm_interconnect_0:jtag_master_master_write
	signal jtag_master_master_writedata                                        : std_logic_vector(31 downto 0);   -- jtag_master:master_writedata -> mm_interconnect_0:jtag_master_master_writedata
	signal mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_readdata  : std_logic_vector(31 downto 0);   -- delay_and_sum_beamformer_0:avalon_slave_readdata -> mm_interconnect_0:delay_and_sum_beamformer_0_avalon_slave_readdata
	signal mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_address   : std_logic_vector(0 downto 0);    -- mm_interconnect_0:delay_and_sum_beamformer_0_avalon_slave_address -> delay_and_sum_beamformer_0:avalon_slave_address
	signal mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_read      : std_logic;                       -- mm_interconnect_0:delay_and_sum_beamformer_0_avalon_slave_read -> delay_and_sum_beamformer_0:avalon_slave_read
	signal mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_write     : std_logic;                       -- mm_interconnect_0:delay_and_sum_beamformer_0_avalon_slave_write -> delay_and_sum_beamformer_0:avalon_slave_write
	signal mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_writedata : std_logic_vector(31 downto 0);   -- mm_interconnect_0:delay_and_sum_beamformer_0_avalon_slave_writedata -> delay_and_sum_beamformer_0:avalon_slave_writedata
	signal mm_interconnect_0_sysid_qsys_0_control_slave_readdata               : std_logic_vector(31 downto 0);   -- sysid_qsys_0:readdata -> mm_interconnect_0:sysid_qsys_0_control_slave_readdata
	signal mm_interconnect_0_sysid_qsys_0_control_slave_address                : std_logic_vector(0 downto 0);    -- mm_interconnect_0:sysid_qsys_0_control_slave_address -> sysid_qsys_0:address
	signal mm_interconnect_0_mic_array_0_s1_readdata                           : std_logic_vector(31 downto 0);   -- mic_array_0:avs_s1_readdata -> mm_interconnect_0:mic_array_0_s1_readdata
	signal mm_interconnect_0_mic_array_0_s1_address                            : std_logic_vector(1 downto 0);    -- mm_interconnect_0:mic_array_0_s1_address -> mic_array_0:avs_s1_address
	signal mm_interconnect_0_mic_array_0_s1_read                               : std_logic;                       -- mm_interconnect_0:mic_array_0_s1_read -> mic_array_0:avs_s1_read
	signal mm_interconnect_0_mic_array_0_s1_write                              : std_logic;                       -- mm_interconnect_0:mic_array_0_s1_write -> mic_array_0:avs_s1_write
	signal mm_interconnect_0_mic_array_0_s1_writedata                          : std_logic_vector(31 downto 0);   -- mm_interconnect_0:mic_array_0_s1_writedata -> mic_array_0:avs_s1_writedata
	signal delay_and_sum_beamformer_0_avalon_streaming_source_valid            : std_logic;                       -- delay_and_sum_beamformer_0:avalon_source_valid -> avalon_st_adapter:in_0_valid
	signal delay_and_sum_beamformer_0_avalon_streaming_source_data             : std_logic_vector(31 downto 0);   -- delay_and_sum_beamformer_0:avalon_source_data -> avalon_st_adapter:in_0_data
	signal delay_and_sum_beamformer_0_avalon_streaming_source_channel          : std_logic;                       -- delay_and_sum_beamformer_0:avalon_source_channel -> avalon_st_adapter:in_0_channel
	signal delay_and_sum_beamformer_0_avalon_streaming_source_error            : std_logic_vector(1 downto 0);    -- delay_and_sum_beamformer_0:avalon_source_error -> avalon_st_adapter:in_0_error
	signal avalon_st_adapter_out_0_valid                                       : std_logic;                       -- avalon_st_adapter:out_0_valid -> mono2stereo_adapter_0:valid_in
	signal avalon_st_adapter_out_0_data                                        : std_logic_vector(31 downto 0);   -- avalon_st_adapter:out_0_data -> mono2stereo_adapter_0:data_in
	signal avalon_st_adapter_out_0_channel                                     : std_logic;                       -- avalon_st_adapter:out_0_channel -> mono2stereo_adapter_0:channel_in
	signal mono2stereo_adapter_0_data_out_valid                                : std_logic;                       -- mono2stereo_adapter_0:valid_out -> avalon_st_adapter_001:in_0_valid
	signal mono2stereo_adapter_0_data_out_data                                 : std_logic_vector(31 downto 0);   -- mono2stereo_adapter_0:data_out -> avalon_st_adapter_001:in_0_data
	signal mono2stereo_adapter_0_data_out_channel                              : std_logic;                       -- mono2stereo_adapter_0:channel_out -> avalon_st_adapter_001:in_0_channel
	signal avalon_st_adapter_001_out_0_valid                                   : std_logic;                       -- avalon_st_adapter_001:out_0_valid -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_DAC2_valid
	signal avalon_st_adapter_001_out_0_data                                    : std_logic_vector(31 downto 0);   -- avalon_st_adapter_001:out_0_data -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_DAC2_data
	signal avalon_st_adapter_001_out_0_channel                                 : std_logic_vector(1 downto 0);    -- avalon_st_adapter_001:out_0_channel -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_DAC2_channel
	signal avalon_st_adapter_001_out_0_error                                   : std_logic_vector(1 downto 0);    -- avalon_st_adapter_001:out_0_error -> FE_Qsys_AD1939_Audio_Research_v1_0:AD1939_DAC2_error
	signal mic_array_0_data_out_valid                                          : std_logic;                       -- mic_array_0:ast_valid -> avalon_st_adapter_002:in_0_valid
	signal mic_array_0_data_out_data                                           : std_logic_vector(31 downto 0);   -- mic_array_0:ast_data -> avalon_st_adapter_002:in_0_data
	signal mic_array_0_data_out_channel                                        : std_logic_vector(3 downto 0);    -- mic_array_0:ast_channel -> avalon_st_adapter_002:in_0_channel
	signal avalon_st_adapter_002_out_0_valid                                   : std_logic;                       -- avalon_st_adapter_002:out_0_valid -> delay_and_sum_beamformer_0:avalon_sink_valid
	signal avalon_st_adapter_002_out_0_data                                    : std_logic_vector(31 downto 0);   -- avalon_st_adapter_002:out_0_data -> delay_and_sum_beamformer_0:avalon_sink_data
	signal avalon_st_adapter_002_out_0_channel                                 : std_logic_vector(3 downto 0);    -- avalon_st_adapter_002:out_0_channel -> delay_and_sum_beamformer_0:avalon_sink_channel
	signal avalon_st_adapter_002_out_0_error                                   : std_logic_vector(1 downto 0);    -- avalon_st_adapter_002:out_0_error -> delay_and_sum_beamformer_0:avalon_sink_error
	signal rst_controller_reset_out_reset                                      : std_logic;                       -- rst_controller:reset_out -> mm_interconnect_0:mic_array_0_reset_reset_bridge_in_reset_reset
	signal codec_clocks_reset_out_reset_ports_inv                              : std_logic;                       -- codec_clocks_reset_out_reset:inv -> [hps:h2f_lw_axi_rst, mic_array_clocks:reset_reset_n, sysid_qsys_0:reset_n]

begin

	fe_qsys_ad1939_audio_research_v1_0 : component soc_system_FE_Qsys_AD1939_Audio_Research_v1_10.soc_system_pkg.AD1939_hps_audio_research
		port map (
			AD1939_DAC1_channel => open,                                --     Headphone_Out.channel
			AD1939_DAC1_data    => open,                                --                  .data
			AD1939_DAC1_error   => open,                                --                  .error
			AD1939_DAC1_valid   => open,                                --                  .valid
			AD1939_DAC2_channel => avalon_st_adapter_001_out_0_channel, --          Line_Out.channel
			AD1939_DAC2_data    => avalon_st_adapter_001_out_0_data,    --                  .data
			AD1939_DAC2_error   => avalon_st_adapter_001_out_0_error,   --                  .error
			AD1939_DAC2_valid   => avalon_st_adapter_001_out_0_valid,   --                  .valid
			AD1939_DAC3_channel => open,                                --          XLR1_Out.channel
			AD1939_DAC3_data    => open,                                --                  .data
			AD1939_DAC3_error   => open,                                --                  .error
			AD1939_DAC3_valid   => open,                                --                  .valid
			AD1939_DAC4_channel => open,                                --          XLR2_Out.channel
			AD1939_DAC4_data    => open,                                --                  .data
			AD1939_DAC4_error   => open,                                --                  .error
			AD1939_DAC4_valid   => open,                                --                  .valid
			AD1939_ADC2_channel => open,                                --           Line_In.channel
			AD1939_ADC2_data    => open,                                --                  .data
			AD1939_ADC2_error   => open,                                --                  .error
			AD1939_ADC2_valid   => open,                                --                  .valid
			AD1939_ADC1_channel => open,                                --     Microphone_In.channel
			AD1939_ADC1_data    => open,                                --                  .data
			AD1939_ADC1_error   => open,                                --                  .error
			AD1939_ADC1_valid   => open,                                --                  .valid
			sys_reset           => codec_clocks_reset_out_reset,        --         sys_reset.reset
			AD1939_ADC_ABCLK    => codec_clocks_ad1939_abclk_out_clk,   --         clk_abclk.clk
			AD1939_ADC_ALRCLK   => codec_clocks_ad1939_alrclk_out_clk,  --        clk_alrclk.clk
			sys_clk             => codec_clocks_sys_clk_clk,            --           sys_clk.clk
			AD1939_ADC_ASDATA1  => ad1939_physical_ad1939_adc_asdata1,  -- connect_to_AD1939.ad1939_adc_asdata1
			AD1939_ADC_ASDATA2  => ad1939_physical_ad1939_adc_asdata2,  --                  .ad1939_adc_asdata2
			AD1939_DAC_DBCLK    => ad1939_physical_ad1939_dac_dbclk,    --                  .ad1939_dac_dbclk
			AD1939_DAC_DLRCLK   => ad1939_physical_ad1939_dac_dlrclk,   --                  .ad1939_dac_dlrclk
			AD1939_DAC_DSDATA1  => ad1939_physical_ad1939_dac_dsdata1,  --                  .ad1939_dac_dsdata1
			AD1939_DAC_DSDATA2  => ad1939_physical_ad1939_dac_dsdata2,  --                  .ad1939_dac_dsdata2
			AD1939_DAC_DSDATA3  => ad1939_physical_ad1939_dac_dsdata3,  --                  .ad1939_dac_dsdata3
			AD1939_DAC_DSDATA4  => ad1939_physical_ad1939_dac_dsdata4   --                  .ad1939_dac_dsdata4
		);

	codec_clocks : component soc_system_codec_clocks_10.soc_system_pkg.soc_system_codec_clocks_10_ns6zpna
		port map (
			ad1939_abclk_in_clk   => ad1939_abclk_clk,                   --   ad1939_abclk_in.clk
			ad1939_abclk_out_clk  => codec_clocks_ad1939_abclk_out_clk,  --  ad1939_abclk_out.clk
			ad1939_alrclk_in_clk  => ad1939_alrclk_clk,                  --  ad1939_alrclk_in.clk
			ad1939_alrclk_out_clk => codec_clocks_ad1939_alrclk_out_clk, -- ad1939_alrclk_out.clk
			ad1939_mclk_in_clk    => ad1939_mclk_clk,                    --    ad1939_mclk_in.clk
			ad1939_mclk_out_clk   => codec_clocks_ad1939_mclk_out_clk,   --   ad1939_mclk_out.clk
			reset_in_reset        => reset_reset,                        --          reset_in.reset
			reset_out_reset       => codec_clocks_reset_out_reset,       --         reset_out.reset
			sys_clk_clk           => codec_clocks_sys_clk_clk            --           sys_clk.clk
		);

	ddr4 : component soc_system_altera_emif_a10_hps_180.soc_system_pkg.soc_system_altera_emif_a10_hps_180_oqueytq
		port map (
			global_reset_n => ddr4_global_reset_reset_sink_reset_n,  -- global_reset_reset_sink.reset_n
			pll_ref_clk    => ddr4_pll_ref_clk_clock_sink_clk,       --  pll_ref_clk_clock_sink.clk
			oct_rzqin      => ddr4_oct_conduit_end_oct_rzqin,        --         oct_conduit_end.oct_rzqin
			mem_ck         => ddr4_mem_conduit_end_mem_ck,           --         mem_conduit_end.mem_ck
			mem_ck_n       => ddr4_mem_conduit_end_mem_ck_n,         --                        .mem_ck_n
			mem_a          => ddr4_mem_conduit_end_mem_a,            --                        .mem_a
			mem_act_n      => ddr4_mem_conduit_end_mem_act_n,        --                        .mem_act_n
			mem_ba         => ddr4_mem_conduit_end_mem_ba,           --                        .mem_ba
			mem_bg         => ddr4_mem_conduit_end_mem_bg,           --                        .mem_bg
			mem_cke        => ddr4_mem_conduit_end_mem_cke,          --                        .mem_cke
			mem_cs_n       => ddr4_mem_conduit_end_mem_cs_n,         --                        .mem_cs_n
			mem_odt        => ddr4_mem_conduit_end_mem_odt,          --                        .mem_odt
			mem_reset_n    => ddr4_mem_conduit_end_mem_reset_n,      --                        .mem_reset_n
			mem_par        => ddr4_mem_conduit_end_mem_par,          --                        .mem_par
			mem_alert_n    => ddr4_mem_conduit_end_mem_alert_n,      --                        .mem_alert_n
			mem_dqs        => ddr4_mem_conduit_end_mem_dqs,          --                        .mem_dqs
			mem_dqs_n      => ddr4_mem_conduit_end_mem_dqs_n,        --                        .mem_dqs_n
			mem_dq         => ddr4_mem_conduit_end_mem_dq,           --                        .mem_dq
			mem_dbi_n      => ddr4_mem_conduit_end_mem_dbi_n,        --                        .mem_dbi_n
			hps_to_emif    => hps_emif_hps_to_emif,                  --    hps_emif_conduit_end.hps_to_emif
			emif_to_hps    => ddr4_hps_emif_conduit_end_emif_to_hps, --                        .emif_to_hps
			hps_to_emif_gp => hps_emif_gp_to_emif,                   --                        .gp_to_emif
			emif_to_hps_gp => ddr4_hps_emif_conduit_end_emif_to_gp   --                        .emif_to_gp
		);

	delay_and_sum_beamformer_0 : component soc_system_delay_and_sum_beamformer_10.soc_system_pkg.DSBF_dataplane_avalon
		port map (
			clk                    => codec_clocks_sys_clk_clk,                                             --                   clock.clk
			reset                  => codec_clocks_reset_out_reset,                                         --                   reset.reset
			avalon_slave_address   => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_address(0), --            avalon_slave.address
			avalon_slave_read      => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_read,       --                        .read
			avalon_slave_readdata  => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_readdata,   --                        .readdata
			avalon_slave_write     => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_write,      --                        .write
			avalon_slave_writedata => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_writedata,  --                        .writedata
			avalon_sink_valid      => avalon_st_adapter_002_out_0_valid,                                    --   avalon_streaming_sink.valid
			avalon_sink_data       => avalon_st_adapter_002_out_0_data,                                     --                        .data
			avalon_sink_channel    => avalon_st_adapter_002_out_0_channel,                                  --                        .channel
			avalon_sink_error      => avalon_st_adapter_002_out_0_error,                                    --                        .error
			avalon_source_valid    => delay_and_sum_beamformer_0_avalon_streaming_source_valid,             -- avalon_streaming_source.valid
			avalon_source_data     => delay_and_sum_beamformer_0_avalon_streaming_source_data,              --                        .data
			avalon_source_channel  => delay_and_sum_beamformer_0_avalon_streaming_source_channel,           --                        .channel
			avalon_source_error    => delay_and_sum_beamformer_0_avalon_streaming_source_error              --                        .error
		);

	hps : component soc_system_altera_arria10_hps_180.soc_system_pkg.soc_system_altera_arria10_hps_180_ruxeq2a
		generic map (
			F2S_Width => 0,
			S2F_Width => 0
		)
		port map (
			h2f_rst_n                 => open,                                    --          h2f_reset.reset_n
			f2h_cold_rst_req_n        => hps_f2h_cold_reset_req_reset_n,          -- f2h_cold_reset_req.reset_n
			f2h_warm_rst_req_n        => hps_f2h_warm_reset_req_reset_n,          -- f2h_warm_reset_req.reset_n
			emif_emif_to_hps          => ddr4_hps_emif_conduit_end_emif_to_hps,   --               emif.emif_to_hps
			emif_hps_to_emif          => hps_emif_hps_to_emif,                    --                   .hps_to_emif
			emif_emif_to_gp           => ddr4_hps_emif_conduit_end_emif_to_gp(0), --                   .emif_to_gp
			emif_gp_to_emif           => hps_emif_gp_to_emif,                     --                   .gp_to_emif
			h2f_lw_axi_clk            => codec_clocks_sys_clk_clk,                --   h2f_lw_axi_clock.clk
			h2f_lw_axi_rst            => codec_clocks_reset_out_reset_ports_inv,  --   h2f_lw_axi_reset.reset_n
			h2f_lw_AWID               => hps_h2f_lw_axi_master_awid,              --  h2f_lw_axi_master.awid
			h2f_lw_AWADDR             => hps_h2f_lw_axi_master_awaddr,            --                   .awaddr
			h2f_lw_AWLEN              => hps_h2f_lw_axi_master_awlen,             --                   .awlen
			h2f_lw_AWSIZE             => hps_h2f_lw_axi_master_awsize,            --                   .awsize
			h2f_lw_AWBURST            => hps_h2f_lw_axi_master_awburst,           --                   .awburst
			h2f_lw_AWLOCK             => hps_h2f_lw_axi_master_awlock,            --                   .awlock
			h2f_lw_AWCACHE            => hps_h2f_lw_axi_master_awcache,           --                   .awcache
			h2f_lw_AWPROT             => hps_h2f_lw_axi_master_awprot,            --                   .awprot
			h2f_lw_AWVALID            => hps_h2f_lw_axi_master_awvalid,           --                   .awvalid
			h2f_lw_AWREADY            => hps_h2f_lw_axi_master_awready,           --                   .awready
			h2f_lw_AWUSER             => hps_h2f_lw_axi_master_awuser,            --                   .awuser
			h2f_lw_WID                => hps_h2f_lw_axi_master_wid,               --                   .wid
			h2f_lw_WDATA              => hps_h2f_lw_axi_master_wdata,             --                   .wdata
			h2f_lw_WSTRB              => hps_h2f_lw_axi_master_wstrb,             --                   .wstrb
			h2f_lw_WLAST              => hps_h2f_lw_axi_master_wlast,             --                   .wlast
			h2f_lw_WVALID             => hps_h2f_lw_axi_master_wvalid,            --                   .wvalid
			h2f_lw_WREADY             => hps_h2f_lw_axi_master_wready,            --                   .wready
			h2f_lw_BID                => hps_h2f_lw_axi_master_bid,               --                   .bid
			h2f_lw_BRESP              => hps_h2f_lw_axi_master_bresp,             --                   .bresp
			h2f_lw_BVALID             => hps_h2f_lw_axi_master_bvalid,            --                   .bvalid
			h2f_lw_BREADY             => hps_h2f_lw_axi_master_bready,            --                   .bready
			h2f_lw_ARID               => hps_h2f_lw_axi_master_arid,              --                   .arid
			h2f_lw_ARADDR             => hps_h2f_lw_axi_master_araddr,            --                   .araddr
			h2f_lw_ARLEN              => hps_h2f_lw_axi_master_arlen,             --                   .arlen
			h2f_lw_ARSIZE             => hps_h2f_lw_axi_master_arsize,            --                   .arsize
			h2f_lw_ARBURST            => hps_h2f_lw_axi_master_arburst,           --                   .arburst
			h2f_lw_ARLOCK             => hps_h2f_lw_axi_master_arlock,            --                   .arlock
			h2f_lw_ARCACHE            => hps_h2f_lw_axi_master_arcache,           --                   .arcache
			h2f_lw_ARPROT             => hps_h2f_lw_axi_master_arprot,            --                   .arprot
			h2f_lw_ARVALID            => hps_h2f_lw_axi_master_arvalid,           --                   .arvalid
			h2f_lw_ARREADY            => hps_h2f_lw_axi_master_arready,           --                   .arready
			h2f_lw_ARUSER             => hps_h2f_lw_axi_master_aruser,            --                   .aruser
			h2f_lw_RID                => hps_h2f_lw_axi_master_rid,               --                   .rid
			h2f_lw_RDATA              => hps_h2f_lw_axi_master_rdata,             --                   .rdata
			h2f_lw_RRESP              => hps_h2f_lw_axi_master_rresp,             --                   .rresp
			h2f_lw_RLAST              => hps_h2f_lw_axi_master_rlast,             --                   .rlast
			h2f_lw_RVALID             => hps_h2f_lw_axi_master_rvalid,            --                   .rvalid
			h2f_lw_RREADY             => hps_h2f_lw_axi_master_rready,            --                   .rready
			f2h_irq_p0                => hps_f2h_irq0_irq,                        --           f2h_irq0.irq
			f2h_irq_p1                => hps_f2h_irq1_irq,                        --           f2h_irq1.irq
			spim1_mosi_o              => hps_spim1_mosi_o,                        --              spim1.mosi_o
			spim1_miso_i              => hps_spim1_miso_i,                        --                   .miso_i
			spim1_ss_in_n             => hps_spim1_ss_in_n,                       --                   .ss_in_n
			spim1_mosi_oe             => hps_spim1_mosi_oe,                       --                   .mosi_oe
			spim1_ss0_n_o             => hps_spim1_ss0_n_o,                       --                   .ss0_n_o
			spim1_ss1_n_o             => hps_spim1_ss1_n_o,                       --                   .ss1_n_o
			spim1_ss2_n_o             => hps_spim1_ss2_n_o,                       --                   .ss2_n_o
			spim1_ss3_n_o             => hps_spim1_ss3_n_o,                       --                   .ss3_n_o
			spim1_sclk_out            => hps_spim1_sclk_out_clk,                  --     spim1_sclk_out.clk
			i2c0_scl_i                => hps_i2c0_scl_in_clk,                     --        i2c0_scl_in.clk
			i2c0_scl_oe               => hps_i2c0_clk_clk,                        --           i2c0_clk.clk
			i2c0_sda_i                => hps_i2c0_sda_i,                          --               i2c0.sda_i
			i2c0_sda_oe               => hps_i2c0_sda_oe,                         --                   .sda_oe
			hps_io_phery_emac1_TX_CLK => hps_io_hps_io_phery_emac1_TX_CLK,        --             hps_io.hps_io_phery_emac1_TX_CLK
			hps_io_phery_emac1_TXD0   => hps_io_hps_io_phery_emac1_TXD0,          --                   .hps_io_phery_emac1_TXD0
			hps_io_phery_emac1_TXD1   => hps_io_hps_io_phery_emac1_TXD1,          --                   .hps_io_phery_emac1_TXD1
			hps_io_phery_emac1_TXD2   => hps_io_hps_io_phery_emac1_TXD2,          --                   .hps_io_phery_emac1_TXD2
			hps_io_phery_emac1_TXD3   => hps_io_hps_io_phery_emac1_TXD3,          --                   .hps_io_phery_emac1_TXD3
			hps_io_phery_emac1_RX_CTL => hps_io_hps_io_phery_emac1_RX_CTL,        --                   .hps_io_phery_emac1_RX_CTL
			hps_io_phery_emac1_TX_CTL => hps_io_hps_io_phery_emac1_TX_CTL,        --                   .hps_io_phery_emac1_TX_CTL
			hps_io_phery_emac1_RX_CLK => hps_io_hps_io_phery_emac1_RX_CLK,        --                   .hps_io_phery_emac1_RX_CLK
			hps_io_phery_emac1_RXD0   => hps_io_hps_io_phery_emac1_RXD0,          --                   .hps_io_phery_emac1_RXD0
			hps_io_phery_emac1_RXD1   => hps_io_hps_io_phery_emac1_RXD1,          --                   .hps_io_phery_emac1_RXD1
			hps_io_phery_emac1_RXD2   => hps_io_hps_io_phery_emac1_RXD2,          --                   .hps_io_phery_emac1_RXD2
			hps_io_phery_emac1_RXD3   => hps_io_hps_io_phery_emac1_RXD3,          --                   .hps_io_phery_emac1_RXD3
			hps_io_phery_emac1_MDIO   => hps_io_hps_io_phery_emac1_MDIO,          --                   .hps_io_phery_emac1_MDIO
			hps_io_phery_emac1_MDC    => hps_io_hps_io_phery_emac1_MDC,           --                   .hps_io_phery_emac1_MDC
			hps_io_phery_emac2_TX_CLK => hps_io_hps_io_phery_emac2_TX_CLK,        --                   .hps_io_phery_emac2_TX_CLK
			hps_io_phery_emac2_TXD0   => hps_io_hps_io_phery_emac2_TXD0,          --                   .hps_io_phery_emac2_TXD0
			hps_io_phery_emac2_TXD1   => hps_io_hps_io_phery_emac2_TXD1,          --                   .hps_io_phery_emac2_TXD1
			hps_io_phery_emac2_TXD2   => hps_io_hps_io_phery_emac2_TXD2,          --                   .hps_io_phery_emac2_TXD2
			hps_io_phery_emac2_TXD3   => hps_io_hps_io_phery_emac2_TXD3,          --                   .hps_io_phery_emac2_TXD3
			hps_io_phery_emac2_RX_CTL => hps_io_hps_io_phery_emac2_RX_CTL,        --                   .hps_io_phery_emac2_RX_CTL
			hps_io_phery_emac2_TX_CTL => hps_io_hps_io_phery_emac2_TX_CTL,        --                   .hps_io_phery_emac2_TX_CTL
			hps_io_phery_emac2_RX_CLK => hps_io_hps_io_phery_emac2_RX_CLK,        --                   .hps_io_phery_emac2_RX_CLK
			hps_io_phery_emac2_RXD0   => hps_io_hps_io_phery_emac2_RXD0,          --                   .hps_io_phery_emac2_RXD0
			hps_io_phery_emac2_RXD1   => hps_io_hps_io_phery_emac2_RXD1,          --                   .hps_io_phery_emac2_RXD1
			hps_io_phery_emac2_RXD2   => hps_io_hps_io_phery_emac2_RXD2,          --                   .hps_io_phery_emac2_RXD2
			hps_io_phery_emac2_RXD3   => hps_io_hps_io_phery_emac2_RXD3,          --                   .hps_io_phery_emac2_RXD3
			hps_io_phery_emac2_MDIO   => hps_io_hps_io_phery_emac2_MDIO,          --                   .hps_io_phery_emac2_MDIO
			hps_io_phery_emac2_MDC    => hps_io_hps_io_phery_emac2_MDC,           --                   .hps_io_phery_emac2_MDC
			hps_io_phery_sdmmc_CMD    => hps_io_hps_io_phery_sdmmc_CMD,           --                   .hps_io_phery_sdmmc_CMD
			hps_io_phery_sdmmc_D0     => hps_io_hps_io_phery_sdmmc_D0,            --                   .hps_io_phery_sdmmc_D0
			hps_io_phery_sdmmc_D1     => hps_io_hps_io_phery_sdmmc_D1,            --                   .hps_io_phery_sdmmc_D1
			hps_io_phery_sdmmc_D2     => hps_io_hps_io_phery_sdmmc_D2,            --                   .hps_io_phery_sdmmc_D2
			hps_io_phery_sdmmc_D3     => hps_io_hps_io_phery_sdmmc_D3,            --                   .hps_io_phery_sdmmc_D3
			hps_io_phery_sdmmc_D4     => hps_io_hps_io_phery_sdmmc_D4,            --                   .hps_io_phery_sdmmc_D4
			hps_io_phery_sdmmc_D5     => hps_io_hps_io_phery_sdmmc_D5,            --                   .hps_io_phery_sdmmc_D5
			hps_io_phery_sdmmc_D6     => hps_io_hps_io_phery_sdmmc_D6,            --                   .hps_io_phery_sdmmc_D6
			hps_io_phery_sdmmc_D7     => hps_io_hps_io_phery_sdmmc_D7,            --                   .hps_io_phery_sdmmc_D7
			hps_io_phery_sdmmc_CCLK   => hps_io_hps_io_phery_sdmmc_CCLK,          --                   .hps_io_phery_sdmmc_CCLK
			hps_io_phery_usb1_DATA0   => hps_io_hps_io_phery_usb1_DATA0,          --                   .hps_io_phery_usb1_DATA0
			hps_io_phery_usb1_DATA1   => hps_io_hps_io_phery_usb1_DATA1,          --                   .hps_io_phery_usb1_DATA1
			hps_io_phery_usb1_DATA2   => hps_io_hps_io_phery_usb1_DATA2,          --                   .hps_io_phery_usb1_DATA2
			hps_io_phery_usb1_DATA3   => hps_io_hps_io_phery_usb1_DATA3,          --                   .hps_io_phery_usb1_DATA3
			hps_io_phery_usb1_DATA4   => hps_io_hps_io_phery_usb1_DATA4,          --                   .hps_io_phery_usb1_DATA4
			hps_io_phery_usb1_DATA5   => hps_io_hps_io_phery_usb1_DATA5,          --                   .hps_io_phery_usb1_DATA5
			hps_io_phery_usb1_DATA6   => hps_io_hps_io_phery_usb1_DATA6,          --                   .hps_io_phery_usb1_DATA6
			hps_io_phery_usb1_DATA7   => hps_io_hps_io_phery_usb1_DATA7,          --                   .hps_io_phery_usb1_DATA7
			hps_io_phery_usb1_CLK     => hps_io_hps_io_phery_usb1_CLK,            --                   .hps_io_phery_usb1_CLK
			hps_io_phery_usb1_STP     => hps_io_hps_io_phery_usb1_STP,            --                   .hps_io_phery_usb1_STP
			hps_io_phery_usb1_DIR     => hps_io_hps_io_phery_usb1_DIR,            --                   .hps_io_phery_usb1_DIR
			hps_io_phery_usb1_NXT     => hps_io_hps_io_phery_usb1_NXT,            --                   .hps_io_phery_usb1_NXT
			hps_io_phery_uart0_RX     => hps_io_hps_io_phery_uart0_RX,            --                   .hps_io_phery_uart0_RX
			hps_io_phery_uart0_TX     => hps_io_hps_io_phery_uart0_TX,            --                   .hps_io_phery_uart0_TX
			hps_io_phery_uart0_CTS_N  => hps_io_hps_io_phery_uart0_CTS_N,         --                   .hps_io_phery_uart0_CTS_N
			hps_io_phery_uart0_RTS_N  => hps_io_hps_io_phery_uart0_RTS_N          --                   .hps_io_phery_uart0_RTS_N
		);

	jtag_master : component soc_system_altera_jtag_avalon_master_180.soc_system_pkg.soc_system_altera_jtag_avalon_master_180_sb3msya
		generic map (
			USE_PLI     => 0,
			PLI_PORT    => 50000,
			FIFO_DEPTHS => 2
		)
		port map (
			clk_clk              => codec_clocks_sys_clk_clk,         --          clk.clk
			clk_reset_reset      => codec_clocks_reset_out_reset,     --    clk_reset.reset
			master_address       => jtag_master_master_address,       --       master.address
			master_readdata      => jtag_master_master_readdata,      --             .readdata
			master_read          => jtag_master_master_read,          --             .read
			master_write         => jtag_master_master_write,         --             .write
			master_writedata     => jtag_master_master_writedata,     --             .writedata
			master_waitrequest   => jtag_master_master_waitrequest,   --             .waitrequest
			master_readdatavalid => jtag_master_master_readdatavalid, --             .readdatavalid
			master_byteenable    => jtag_master_master_byteenable,    --             .byteenable
			master_reset_reset   => open                              -- master_reset.reset
		);

	mic_array_0 : component soc_system_mic_array_10.soc_system_pkg.mic_array_avalon
		port map (
			avs_s1_address   => mm_interconnect_0_mic_array_0_s1_address,   --                    s1.address
			avs_s1_write     => mm_interconnect_0_mic_array_0_s1_write,     --                      .write
			avs_s1_writedata => mm_interconnect_0_mic_array_0_s1_writedata, --                      .writedata
			avs_s1_read      => mm_interconnect_0_mic_array_0_s1_read,      --                      .read
			avs_s1_readdata  => mm_interconnect_0_mic_array_0_s1_readdata,  --                      .readdata
			ast_data         => mic_array_0_data_out_data,                  --              data_out.data
			ast_channel      => mic_array_0_data_out_channel,               --                      .channel
			ast_valid        => mic_array_0_data_out_valid,                 --                      .valid
			led_sd           => mic_array_0_led_sd,                         --  connect_to_mic_array.led_sd
			led_ws           => mic_array_0_led_ws,                         --                      .led_ws
			sd               => mic_array_0_sd,                             --                      .sd
			ws               => mic_array_0_ws,                             --                      .ws
			rst              => codec_clocks_reset_out_reset,               --                 reset.reset
			sys_clk          => codec_clocks_sys_clk_clk,                   --               sys_clk.clk
			sck_master       => mic_array_clocks_sck_master_clk,            --  mic_array_master_clk.clk
			sck_rcv          => mic_array_clocks_sck_rcv_ch0_clk            -- mic_array_receive_clk.clk
		);

	mic_array_clocks : component soc_system_mic_array_clocks_10.soc_system_pkg.soc_system_mic_array_clocks_10_hjvfn7a
		port map (
			ad1939_mclk_clk       => codec_clocks_ad1939_mclk_out_clk,       --       ad1939_mclk.clk
			reset_reset_n         => codec_clocks_reset_out_reset_ports_inv, --             reset.reset_n
			sck_master_clk        => mic_array_clocks_sck_master_clk,        --        sck_master.clk
			sck_master_export_clk => mic_array_sck_clk,                      -- sck_master_export.clk
			sck_rcv_ch0_clk       => mic_array_clocks_sck_rcv_ch0_clk        --       sck_rcv_ch0.clk
		);

	mono2stereo_adapter_0 : component soc_system_mono2stereo_adapter_10.soc_system_pkg.mono2stereo_adapter
		generic map (
			sample_rate => 48000,
			clk_freq    => 98304000,
			data_width  => 32
		)
		port map (
			clk         => codec_clocks_sys_clk_clk,               --    clock.clk
			channel_out => mono2stereo_adapter_0_data_out_channel, -- data_out.channel
			data_out    => mono2stereo_adapter_0_data_out_data,    --         .data
			valid_out   => mono2stereo_adapter_0_data_out_valid,   --         .valid
			channel_in  => avalon_st_adapter_out_0_channel,        --  data_in.channel
			data_in     => avalon_st_adapter_out_0_data,           --         .data
			valid_in    => avalon_st_adapter_out_0_valid,          --         .valid
			rst         => codec_clocks_reset_out_reset            --    reset.reset
		);

	sysid_qsys_0 : component soc_system_altera_avalon_sysid_qsys_180.soc_system_pkg.soc_system_altera_avalon_sysid_qsys_180_dzv5wqa
		port map (
			clock    => codec_clocks_sys_clk_clk,                                --           clk.clk
			reset_n  => codec_clocks_reset_out_reset_ports_inv,                  --         reset.reset_n
			readdata => mm_interconnect_0_sysid_qsys_0_control_slave_readdata,   -- control_slave.readdata
			address  => mm_interconnect_0_sysid_qsys_0_control_slave_address(0)  --              .address
		);

	mm_interconnect_0 : component soc_system_altera_mm_interconnect_180.soc_system_pkg.soc_system_altera_mm_interconnect_180_4tjcpzi
		port map (
			hps_h2f_lw_axi_master_awid                        => hps_h2f_lw_axi_master_awid,                                          --                       hps_h2f_lw_axi_master.awid
			hps_h2f_lw_axi_master_awaddr                      => hps_h2f_lw_axi_master_awaddr,                                        --                                            .awaddr
			hps_h2f_lw_axi_master_awlen                       => hps_h2f_lw_axi_master_awlen,                                         --                                            .awlen
			hps_h2f_lw_axi_master_awsize                      => hps_h2f_lw_axi_master_awsize,                                        --                                            .awsize
			hps_h2f_lw_axi_master_awburst                     => hps_h2f_lw_axi_master_awburst,                                       --                                            .awburst
			hps_h2f_lw_axi_master_awlock                      => hps_h2f_lw_axi_master_awlock,                                        --                                            .awlock
			hps_h2f_lw_axi_master_awcache                     => hps_h2f_lw_axi_master_awcache,                                       --                                            .awcache
			hps_h2f_lw_axi_master_awprot                      => hps_h2f_lw_axi_master_awprot,                                        --                                            .awprot
			hps_h2f_lw_axi_master_awuser                      => hps_h2f_lw_axi_master_awuser,                                        --                                            .awuser
			hps_h2f_lw_axi_master_awvalid                     => hps_h2f_lw_axi_master_awvalid,                                       --                                            .awvalid
			hps_h2f_lw_axi_master_awready                     => hps_h2f_lw_axi_master_awready,                                       --                                            .awready
			hps_h2f_lw_axi_master_wid                         => hps_h2f_lw_axi_master_wid,                                           --                                            .wid
			hps_h2f_lw_axi_master_wdata                       => hps_h2f_lw_axi_master_wdata,                                         --                                            .wdata
			hps_h2f_lw_axi_master_wstrb                       => hps_h2f_lw_axi_master_wstrb,                                         --                                            .wstrb
			hps_h2f_lw_axi_master_wlast                       => hps_h2f_lw_axi_master_wlast,                                         --                                            .wlast
			hps_h2f_lw_axi_master_wvalid                      => hps_h2f_lw_axi_master_wvalid,                                        --                                            .wvalid
			hps_h2f_lw_axi_master_wready                      => hps_h2f_lw_axi_master_wready,                                        --                                            .wready
			hps_h2f_lw_axi_master_bid                         => hps_h2f_lw_axi_master_bid,                                           --                                            .bid
			hps_h2f_lw_axi_master_bresp                       => hps_h2f_lw_axi_master_bresp,                                         --                                            .bresp
			hps_h2f_lw_axi_master_bvalid                      => hps_h2f_lw_axi_master_bvalid,                                        --                                            .bvalid
			hps_h2f_lw_axi_master_bready                      => hps_h2f_lw_axi_master_bready,                                        --                                            .bready
			hps_h2f_lw_axi_master_arid                        => hps_h2f_lw_axi_master_arid,                                          --                                            .arid
			hps_h2f_lw_axi_master_araddr                      => hps_h2f_lw_axi_master_araddr,                                        --                                            .araddr
			hps_h2f_lw_axi_master_arlen                       => hps_h2f_lw_axi_master_arlen,                                         --                                            .arlen
			hps_h2f_lw_axi_master_arsize                      => hps_h2f_lw_axi_master_arsize,                                        --                                            .arsize
			hps_h2f_lw_axi_master_arburst                     => hps_h2f_lw_axi_master_arburst,                                       --                                            .arburst
			hps_h2f_lw_axi_master_arlock                      => hps_h2f_lw_axi_master_arlock,                                        --                                            .arlock
			hps_h2f_lw_axi_master_arcache                     => hps_h2f_lw_axi_master_arcache,                                       --                                            .arcache
			hps_h2f_lw_axi_master_arprot                      => hps_h2f_lw_axi_master_arprot,                                        --                                            .arprot
			hps_h2f_lw_axi_master_aruser                      => hps_h2f_lw_axi_master_aruser,                                        --                                            .aruser
			hps_h2f_lw_axi_master_arvalid                     => hps_h2f_lw_axi_master_arvalid,                                       --                                            .arvalid
			hps_h2f_lw_axi_master_arready                     => hps_h2f_lw_axi_master_arready,                                       --                                            .arready
			hps_h2f_lw_axi_master_rid                         => hps_h2f_lw_axi_master_rid,                                           --                                            .rid
			hps_h2f_lw_axi_master_rdata                       => hps_h2f_lw_axi_master_rdata,                                         --                                            .rdata
			hps_h2f_lw_axi_master_rresp                       => hps_h2f_lw_axi_master_rresp,                                         --                                            .rresp
			hps_h2f_lw_axi_master_rlast                       => hps_h2f_lw_axi_master_rlast,                                         --                                            .rlast
			hps_h2f_lw_axi_master_rvalid                      => hps_h2f_lw_axi_master_rvalid,                                        --                                            .rvalid
			hps_h2f_lw_axi_master_rready                      => hps_h2f_lw_axi_master_rready,                                        --                                            .rready
			codec_clocks_sys_clk_clk                          => codec_clocks_sys_clk_clk,                                            --                        codec_clocks_sys_clk.clk
			mic_array_clocks_sck_master_clk                   => mic_array_clocks_sck_master_clk,                                     --                 mic_array_clocks_sck_master.clk
			hps_h2f_lw_axi_reset_reset_bridge_in_reset_reset  => codec_clocks_reset_out_reset,                                        --  hps_h2f_lw_axi_reset_reset_bridge_in_reset.reset
			jtag_master_clk_reset_reset_bridge_in_reset_reset => codec_clocks_reset_out_reset,                                        -- jtag_master_clk_reset_reset_bridge_in_reset.reset
			mic_array_0_reset_reset_bridge_in_reset_reset     => rst_controller_reset_out_reset,                                      --     mic_array_0_reset_reset_bridge_in_reset.reset
			jtag_master_master_address                        => jtag_master_master_address,                                          --                          jtag_master_master.address
			jtag_master_master_waitrequest                    => jtag_master_master_waitrequest,                                      --                                            .waitrequest
			jtag_master_master_byteenable                     => jtag_master_master_byteenable,                                       --                                            .byteenable
			jtag_master_master_read                           => jtag_master_master_read,                                             --                                            .read
			jtag_master_master_readdata                       => jtag_master_master_readdata,                                         --                                            .readdata
			jtag_master_master_readdatavalid                  => jtag_master_master_readdatavalid,                                    --                                            .readdatavalid
			jtag_master_master_write                          => jtag_master_master_write,                                            --                                            .write
			jtag_master_master_writedata                      => jtag_master_master_writedata,                                        --                                            .writedata
			delay_and_sum_beamformer_0_avalon_slave_address   => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_address,   --     delay_and_sum_beamformer_0_avalon_slave.address
			delay_and_sum_beamformer_0_avalon_slave_write     => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_write,     --                                            .write
			delay_and_sum_beamformer_0_avalon_slave_read      => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_read,      --                                            .read
			delay_and_sum_beamformer_0_avalon_slave_readdata  => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_readdata,  --                                            .readdata
			delay_and_sum_beamformer_0_avalon_slave_writedata => mm_interconnect_0_delay_and_sum_beamformer_0_avalon_slave_writedata, --                                            .writedata
			mic_array_0_s1_address                            => mm_interconnect_0_mic_array_0_s1_address,                            --                              mic_array_0_s1.address
			mic_array_0_s1_write                              => mm_interconnect_0_mic_array_0_s1_write,                              --                                            .write
			mic_array_0_s1_read                               => mm_interconnect_0_mic_array_0_s1_read,                               --                                            .read
			mic_array_0_s1_readdata                           => mm_interconnect_0_mic_array_0_s1_readdata,                           --                                            .readdata
			mic_array_0_s1_writedata                          => mm_interconnect_0_mic_array_0_s1_writedata,                          --                                            .writedata
			sysid_qsys_0_control_slave_address                => mm_interconnect_0_sysid_qsys_0_control_slave_address,                --                  sysid_qsys_0_control_slave.address
			sysid_qsys_0_control_slave_readdata               => mm_interconnect_0_sysid_qsys_0_control_slave_readdata                --                                            .readdata
		);

	avalon_st_adapter : component soc_system_altera_avalon_st_adapter_180.soc_system_pkg.soc_system_altera_avalon_st_adapter_180_g7t4xhq
		generic map (
			inBitsPerSymbol => 32,
			inUsePackets    => 0,
			inDataWidth     => 32,
			inChannelWidth  => 1,
			inErrorWidth    => 2,
			inUseEmptyPort  => 0,
			inUseValid      => 1,
			inUseReady      => 0,
			inReadyLatency  => 0,
			outDataWidth    => 32,
			outChannelWidth => 1,
			outErrorWidth   => 0,
			outUseEmptyPort => 0,
			outUseValid     => 1,
			outUseReady     => 0,
			outReadyLatency => 0
		)
		port map (
			in_clk_0_clk   => codec_clocks_sys_clk_clk,                                   -- in_clk_0.clk
			in_rst_0_reset => codec_clocks_reset_out_reset,                               -- in_rst_0.reset
			in_0_data      => delay_and_sum_beamformer_0_avalon_streaming_source_data,    --     in_0.data
			in_0_valid     => delay_and_sum_beamformer_0_avalon_streaming_source_valid,   --         .valid
			in_0_error     => delay_and_sum_beamformer_0_avalon_streaming_source_error,   --         .error
			in_0_channel   => delay_and_sum_beamformer_0_avalon_streaming_source_channel, --         .channel
			out_0_data     => avalon_st_adapter_out_0_data,                               --    out_0.data
			out_0_valid    => avalon_st_adapter_out_0_valid,                              --         .valid
			out_0_channel  => avalon_st_adapter_out_0_channel                             --         .channel
		);

	avalon_st_adapter_001 : component soc_system_altera_avalon_st_adapter_180.soc_system_pkg.soc_system_altera_avalon_st_adapter_180_gbp22va
		generic map (
			inBitsPerSymbol => 32,
			inUsePackets    => 0,
			inDataWidth     => 32,
			inChannelWidth  => 1,
			inErrorWidth    => 0,
			inUseEmptyPort  => 0,
			inUseValid      => 1,
			inUseReady      => 0,
			inReadyLatency  => 0,
			outDataWidth    => 32,
			outChannelWidth => 2,
			outErrorWidth   => 2,
			outUseEmptyPort => 0,
			outUseValid     => 1,
			outUseReady     => 0,
			outReadyLatency => 0
		)
		port map (
			in_clk_0_clk   => codec_clocks_sys_clk_clk,               -- in_clk_0.clk
			in_rst_0_reset => codec_clocks_reset_out_reset,           -- in_rst_0.reset
			in_0_data      => mono2stereo_adapter_0_data_out_data,    --     in_0.data
			in_0_valid     => mono2stereo_adapter_0_data_out_valid,   --         .valid
			in_0_channel   => mono2stereo_adapter_0_data_out_channel, --         .channel
			out_0_data     => avalon_st_adapter_001_out_0_data,       --    out_0.data
			out_0_valid    => avalon_st_adapter_001_out_0_valid,      --         .valid
			out_0_error    => avalon_st_adapter_001_out_0_error,      --         .error
			out_0_channel  => avalon_st_adapter_001_out_0_channel     --         .channel
		);

	avalon_st_adapter_002 : component soc_system_altera_avalon_st_adapter_180.soc_system_pkg.soc_system_altera_avalon_st_adapter_180_f2h67ry
		generic map (
			inBitsPerSymbol => 32,
			inUsePackets    => 0,
			inDataWidth     => 32,
			inChannelWidth  => 4,
			inErrorWidth    => 0,
			inUseEmptyPort  => 0,
			inUseValid      => 1,
			inUseReady      => 0,
			inReadyLatency  => 0,
			outDataWidth    => 32,
			outChannelWidth => 4,
			outErrorWidth   => 2,
			outUseEmptyPort => 0,
			outUseValid     => 1,
			outUseReady     => 0,
			outReadyLatency => 0
		)
		port map (
			in_clk_0_clk   => codec_clocks_sys_clk_clk,            -- in_clk_0.clk
			in_rst_0_reset => codec_clocks_reset_out_reset,        -- in_rst_0.reset
			in_0_data      => mic_array_0_data_out_data,           --     in_0.data
			in_0_valid     => mic_array_0_data_out_valid,          --         .valid
			in_0_channel   => mic_array_0_data_out_channel,        --         .channel
			out_0_data     => avalon_st_adapter_002_out_0_data,    --    out_0.data
			out_0_valid    => avalon_st_adapter_002_out_0_valid,   --         .valid
			out_0_error    => avalon_st_adapter_002_out_0_error,   --         .error
			out_0_channel  => avalon_st_adapter_002_out_0_channel  --         .channel
		);

	rst_controller : component soc_system_altera_reset_controller_180.soc_system_pkg.altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => codec_clocks_reset_out_reset,    -- reset_in0.reset
			clk            => mic_array_clocks_sck_master_clk, --       clk.clk
			reset_out      => rst_controller_reset_out_reset,  -- reset_out.reset
			reset_req      => open,                            -- (terminated)
			reset_req_in0  => '0',                             -- (terminated)
			reset_in1      => '0',                             -- (terminated)
			reset_req_in1  => '0',                             -- (terminated)
			reset_in2      => '0',                             -- (terminated)
			reset_req_in2  => '0',                             -- (terminated)
			reset_in3      => '0',                             -- (terminated)
			reset_req_in3  => '0',                             -- (terminated)
			reset_in4      => '0',                             -- (terminated)
			reset_req_in4  => '0',                             -- (terminated)
			reset_in5      => '0',                             -- (terminated)
			reset_req_in5  => '0',                             -- (terminated)
			reset_in6      => '0',                             -- (terminated)
			reset_req_in6  => '0',                             -- (terminated)
			reset_in7      => '0',                             -- (terminated)
			reset_req_in7  => '0',                             -- (terminated)
			reset_in8      => '0',                             -- (terminated)
			reset_req_in8  => '0',                             -- (terminated)
			reset_in9      => '0',                             -- (terminated)
			reset_req_in9  => '0',                             -- (terminated)
			reset_in10     => '0',                             -- (terminated)
			reset_req_in10 => '0',                             -- (terminated)
			reset_in11     => '0',                             -- (terminated)
			reset_req_in11 => '0',                             -- (terminated)
			reset_in12     => '0',                             -- (terminated)
			reset_req_in12 => '0',                             -- (terminated)
			reset_in13     => '0',                             -- (terminated)
			reset_req_in13 => '0',                             -- (terminated)
			reset_in14     => '0',                             -- (terminated)
			reset_req_in14 => '0',                             -- (terminated)
			reset_in15     => '0',                             -- (terminated)
			reset_req_in15 => '0'                              -- (terminated)
		);

	codec_clocks_reset_out_reset_ports_inv <= not codec_clocks_reset_out_reset;

end architecture rtl; -- of soc_system
