config soc_system_altera_arria10_hps_180_4pootmi_cfg;
		design soc_system_altera_arria10_hps_180_4pootmi;
		instance soc_system_altera_arria10_hps_180_4pootmi.fpga_interfaces use soc_system_altera_arria10_interface_generator_140.soc_system_altera_arria10_interface_generator_140_vbjqidy;
		instance soc_system_altera_arria10_hps_180_4pootmi.hps_io use soc_system_altera_arria10_hps_io_180.soc_system_altera_arria10_hps_io_180_ygolrsa;
endconfig

