	A10SoM_System u0 (
		.clk_100_clk                            (<connected-to-clk_100_clk>),                            //                           clk_100.clk
		.ddr_ref_clk_clk                        (<connected-to-ddr_ref_clk_clk>),                        //                       ddr_ref_clk.clk
		.emif_0_global_reset_reset_sink_reset_n (<connected-to-emif_0_global_reset_reset_sink_reset_n>), //    emif_0_global_reset_reset_sink.reset_n
		.hps_0_h2f_reset_reset_n                (<connected-to-hps_0_h2f_reset_reset_n>),                //                   hps_0_h2f_reset.reset_n
		.hps_io_hps_io_phery_emac1_TX_CLK       (<connected-to-hps_io_hps_io_phery_emac1_TX_CLK>),       //                            hps_io.hps_io_phery_emac1_TX_CLK
		.hps_io_hps_io_phery_emac1_TXD0         (<connected-to-hps_io_hps_io_phery_emac1_TXD0>),         //                                  .hps_io_phery_emac1_TXD0
		.hps_io_hps_io_phery_emac1_TXD1         (<connected-to-hps_io_hps_io_phery_emac1_TXD1>),         //                                  .hps_io_phery_emac1_TXD1
		.hps_io_hps_io_phery_emac1_TXD2         (<connected-to-hps_io_hps_io_phery_emac1_TXD2>),         //                                  .hps_io_phery_emac1_TXD2
		.hps_io_hps_io_phery_emac1_TXD3         (<connected-to-hps_io_hps_io_phery_emac1_TXD3>),         //                                  .hps_io_phery_emac1_TXD3
		.hps_io_hps_io_phery_emac1_RX_CTL       (<connected-to-hps_io_hps_io_phery_emac1_RX_CTL>),       //                                  .hps_io_phery_emac1_RX_CTL
		.hps_io_hps_io_phery_emac1_TX_CTL       (<connected-to-hps_io_hps_io_phery_emac1_TX_CTL>),       //                                  .hps_io_phery_emac1_TX_CTL
		.hps_io_hps_io_phery_emac1_RX_CLK       (<connected-to-hps_io_hps_io_phery_emac1_RX_CLK>),       //                                  .hps_io_phery_emac1_RX_CLK
		.hps_io_hps_io_phery_emac1_RXD0         (<connected-to-hps_io_hps_io_phery_emac1_RXD0>),         //                                  .hps_io_phery_emac1_RXD0
		.hps_io_hps_io_phery_emac1_RXD1         (<connected-to-hps_io_hps_io_phery_emac1_RXD1>),         //                                  .hps_io_phery_emac1_RXD1
		.hps_io_hps_io_phery_emac1_RXD2         (<connected-to-hps_io_hps_io_phery_emac1_RXD2>),         //                                  .hps_io_phery_emac1_RXD2
		.hps_io_hps_io_phery_emac1_RXD3         (<connected-to-hps_io_hps_io_phery_emac1_RXD3>),         //                                  .hps_io_phery_emac1_RXD3
		.hps_io_hps_io_phery_emac1_MDIO         (<connected-to-hps_io_hps_io_phery_emac1_MDIO>),         //                                  .hps_io_phery_emac1_MDIO
		.hps_io_hps_io_phery_emac1_MDC          (<connected-to-hps_io_hps_io_phery_emac1_MDC>),          //                                  .hps_io_phery_emac1_MDC
		.hps_io_hps_io_phery_sdmmc_CMD          (<connected-to-hps_io_hps_io_phery_sdmmc_CMD>),          //                                  .hps_io_phery_sdmmc_CMD
		.hps_io_hps_io_phery_sdmmc_D0           (<connected-to-hps_io_hps_io_phery_sdmmc_D0>),           //                                  .hps_io_phery_sdmmc_D0
		.hps_io_hps_io_phery_sdmmc_D1           (<connected-to-hps_io_hps_io_phery_sdmmc_D1>),           //                                  .hps_io_phery_sdmmc_D1
		.hps_io_hps_io_phery_sdmmc_D2           (<connected-to-hps_io_hps_io_phery_sdmmc_D2>),           //                                  .hps_io_phery_sdmmc_D2
		.hps_io_hps_io_phery_sdmmc_D3           (<connected-to-hps_io_hps_io_phery_sdmmc_D3>),           //                                  .hps_io_phery_sdmmc_D3
		.hps_io_hps_io_phery_sdmmc_CCLK         (<connected-to-hps_io_hps_io_phery_sdmmc_CCLK>),         //                                  .hps_io_phery_sdmmc_CCLK
		.hps_io_hps_io_phery_usb1_DATA0         (<connected-to-hps_io_hps_io_phery_usb1_DATA0>),         //                                  .hps_io_phery_usb1_DATA0
		.hps_io_hps_io_phery_usb1_DATA1         (<connected-to-hps_io_hps_io_phery_usb1_DATA1>),         //                                  .hps_io_phery_usb1_DATA1
		.hps_io_hps_io_phery_usb1_DATA2         (<connected-to-hps_io_hps_io_phery_usb1_DATA2>),         //                                  .hps_io_phery_usb1_DATA2
		.hps_io_hps_io_phery_usb1_DATA3         (<connected-to-hps_io_hps_io_phery_usb1_DATA3>),         //                                  .hps_io_phery_usb1_DATA3
		.hps_io_hps_io_phery_usb1_DATA4         (<connected-to-hps_io_hps_io_phery_usb1_DATA4>),         //                                  .hps_io_phery_usb1_DATA4
		.hps_io_hps_io_phery_usb1_DATA5         (<connected-to-hps_io_hps_io_phery_usb1_DATA5>),         //                                  .hps_io_phery_usb1_DATA5
		.hps_io_hps_io_phery_usb1_DATA6         (<connected-to-hps_io_hps_io_phery_usb1_DATA6>),         //                                  .hps_io_phery_usb1_DATA6
		.hps_io_hps_io_phery_usb1_DATA7         (<connected-to-hps_io_hps_io_phery_usb1_DATA7>),         //                                  .hps_io_phery_usb1_DATA7
		.hps_io_hps_io_phery_usb1_CLK           (<connected-to-hps_io_hps_io_phery_usb1_CLK>),           //                                  .hps_io_phery_usb1_CLK
		.hps_io_hps_io_phery_usb1_STP           (<connected-to-hps_io_hps_io_phery_usb1_STP>),           //                                  .hps_io_phery_usb1_STP
		.hps_io_hps_io_phery_usb1_DIR           (<connected-to-hps_io_hps_io_phery_usb1_DIR>),           //                                  .hps_io_phery_usb1_DIR
		.hps_io_hps_io_phery_usb1_NXT           (<connected-to-hps_io_hps_io_phery_usb1_NXT>),           //                                  .hps_io_phery_usb1_NXT
		.hps_io_hps_io_phery_uart1_RX           (<connected-to-hps_io_hps_io_phery_uart1_RX>),           //                                  .hps_io_phery_uart1_RX
		.hps_io_hps_io_phery_uart1_TX           (<connected-to-hps_io_hps_io_phery_uart1_TX>),           //                                  .hps_io_phery_uart1_TX
		.hps_io_hps_io_phery_i2c0_SDA           (<connected-to-hps_io_hps_io_phery_i2c0_SDA>),           //                                  .hps_io_phery_i2c0_SDA
		.hps_io_hps_io_phery_i2c0_SCL           (<connected-to-hps_io_hps_io_phery_i2c0_SCL>),           //                                  .hps_io_phery_i2c0_SCL
		.hps_io_hps_io_gpio_gpio2_io6           (<connected-to-hps_io_hps_io_gpio_gpio2_io6>),           //                                  .hps_io_gpio_gpio2_io6
		.hps_io_hps_io_gpio_gpio2_io8           (<connected-to-hps_io_hps_io_gpio_gpio2_io8>),           //                                  .hps_io_gpio_gpio2_io8
		.hps_io_hps_io_gpio_gpio0_io0           (<connected-to-hps_io_hps_io_gpio_gpio0_io0>),           //                                  .hps_io_gpio_gpio0_io0
		.hps_io_hps_io_gpio_gpio0_io1           (<connected-to-hps_io_hps_io_gpio_gpio0_io1>),           //                                  .hps_io_gpio_gpio0_io1
		.hps_io_hps_io_gpio_gpio0_io2           (<connected-to-hps_io_hps_io_gpio_gpio0_io2>),           //                                  .hps_io_gpio_gpio0_io2
		.hps_io_hps_io_gpio_gpio0_io3           (<connected-to-hps_io_hps_io_gpio_gpio0_io3>),           //                                  .hps_io_gpio_gpio0_io3
		.hps_io_hps_io_gpio_gpio0_io6           (<connected-to-hps_io_hps_io_gpio_gpio0_io6>),           //                                  .hps_io_gpio_gpio0_io6
		.hps_io_hps_io_gpio_gpio0_io7           (<connected-to-hps_io_hps_io_gpio_gpio0_io7>),           //                                  .hps_io_gpio_gpio0_io7
		.hps_io_hps_io_gpio_gpio0_io10          (<connected-to-hps_io_hps_io_gpio_gpio0_io10>),          //                                  .hps_io_gpio_gpio0_io10
		.hps_io_hps_io_gpio_gpio0_io11          (<connected-to-hps_io_hps_io_gpio_gpio0_io11>),          //                                  .hps_io_gpio_gpio0_io11
		.hps_io_hps_io_gpio_gpio1_io12          (<connected-to-hps_io_hps_io_gpio_gpio1_io12>),          //                                  .hps_io_gpio_gpio1_io12
		.hps_io_hps_io_gpio_gpio1_io13          (<connected-to-hps_io_hps_io_gpio_gpio1_io13>),          //                                  .hps_io_gpio_gpio1_io13
		.hps_io_hps_io_gpio_gpio1_io14          (<connected-to-hps_io_hps_io_gpio_gpio1_io14>),          //                                  .hps_io_gpio_gpio1_io14
		.hps_io_hps_io_gpio_gpio1_io15          (<connected-to-hps_io_hps_io_gpio_gpio1_io15>),          //                                  .hps_io_gpio_gpio1_io15
		.hps_io_hps_io_gpio_gpio1_io16          (<connected-to-hps_io_hps_io_gpio_gpio1_io16>),          //                                  .hps_io_gpio_gpio1_io16
		.hps_io_hps_io_gpio_gpio1_io17          (<connected-to-hps_io_hps_io_gpio_gpio1_io17>),          //                                  .hps_io_gpio_gpio1_io17
		.hps_io_hps_io_gpio_gpio1_io18          (<connected-to-hps_io_hps_io_gpio_gpio1_io18>),          //                                  .hps_io_gpio_gpio1_io18
		.hps_io_hps_io_gpio_gpio1_io19          (<connected-to-hps_io_hps_io_gpio_gpio1_io19>),          //                                  .hps_io_gpio_gpio1_io19
		.hps_io_hps_io_gpio_gpio1_io20          (<connected-to-hps_io_hps_io_gpio_gpio1_io20>),          //                                  .hps_io_gpio_gpio1_io20
		.hps_io_hps_io_gpio_gpio1_io21          (<connected-to-hps_io_hps_io_gpio_gpio1_io21>),          //                                  .hps_io_gpio_gpio1_io21
		.hps_io_hps_io_gpio_gpio1_io22          (<connected-to-hps_io_hps_io_gpio_gpio1_io22>),          //                                  .hps_io_gpio_gpio1_io22
		.hps_io_hps_io_gpio_gpio1_io23          (<connected-to-hps_io_hps_io_gpio_gpio1_io23>),          //                                  .hps_io_gpio_gpio1_io23
		.mem_mem_ck                             (<connected-to-mem_mem_ck>),                             //                               mem.mem_ck
		.mem_mem_ck_n                           (<connected-to-mem_mem_ck_n>),                           //                                  .mem_ck_n
		.mem_mem_a                              (<connected-to-mem_mem_a>),                              //                                  .mem_a
		.mem_mem_act_n                          (<connected-to-mem_mem_act_n>),                          //                                  .mem_act_n
		.mem_mem_ba                             (<connected-to-mem_mem_ba>),                             //                                  .mem_ba
		.mem_mem_bg                             (<connected-to-mem_mem_bg>),                             //                                  .mem_bg
		.mem_mem_cke                            (<connected-to-mem_mem_cke>),                            //                                  .mem_cke
		.mem_mem_cs_n                           (<connected-to-mem_mem_cs_n>),                           //                                  .mem_cs_n
		.mem_mem_odt                            (<connected-to-mem_mem_odt>),                            //                                  .mem_odt
		.mem_mem_reset_n                        (<connected-to-mem_mem_reset_n>),                        //                                  .mem_reset_n
		.mem_mem_par                            (<connected-to-mem_mem_par>),                            //                                  .mem_par
		.mem_mem_alert_n                        (<connected-to-mem_mem_alert_n>),                        //                                  .mem_alert_n
		.mem_mem_dqs                            (<connected-to-mem_mem_dqs>),                            //                                  .mem_dqs
		.mem_mem_dqs_n                          (<connected-to-mem_mem_dqs_n>),                          //                                  .mem_dqs_n
		.mem_mem_dq                             (<connected-to-mem_mem_dq>),                             //                                  .mem_dq
		.mem_mem_dbi_n                          (<connected-to-mem_mem_dbi_n>),                          //                                  .mem_dbi_n
		.oct_oct_rzqin                          (<connected-to-oct_oct_rzqin>),                          //                               oct.oct_rzqin
		.reset_reset_n                          (<connected-to-reset_reset_n>),                          //                             reset.reset_n
		.som_config_pio_export                  (<connected-to-som_config_pio_export>),                  //                    som_config_pio.export
		.ad1939_alrclk_clk                      (<connected-to-ad1939_alrclk_clk>),                      //                     ad1939_alrclk.clk
		.ad1939_abclk_clk                       (<connected-to-ad1939_abclk_clk>),                       //                      ad1939_abclk.clk
		.ad1939_physical_ad1939_adc_asdata1     (<connected-to-ad1939_physical_ad1939_adc_asdata1>),     //                   ad1939_physical.ad1939_adc_asdata1
		.ad1939_physical_ad1939_adc_asdata2     (<connected-to-ad1939_physical_ad1939_adc_asdata2>),     //                                  .ad1939_adc_asdata2
		.ad1939_physical_ad1939_dac_dbclk       (<connected-to-ad1939_physical_ad1939_dac_dbclk>),       //                                  .ad1939_dac_dbclk
		.ad1939_physical_ad1939_dac_dlrclk      (<connected-to-ad1939_physical_ad1939_dac_dlrclk>),      //                                  .ad1939_dac_dlrclk
		.ad1939_physical_ad1939_dac_dsdata1     (<connected-to-ad1939_physical_ad1939_dac_dsdata1>),     //                                  .ad1939_dac_dsdata1
		.ad1939_physical_ad1939_dac_dsdata2     (<connected-to-ad1939_physical_ad1939_dac_dsdata2>),     //                                  .ad1939_dac_dsdata2
		.ad1939_physical_ad1939_dac_dsdata3     (<connected-to-ad1939_physical_ad1939_dac_dsdata3>),     //                                  .ad1939_dac_dsdata3
		.ad1939_physical_ad1939_dac_dsdata4     (<connected-to-ad1939_physical_ad1939_dac_dsdata4>),     //                                  .ad1939_dac_dsdata4
		.ad1939_mclk_clk                        (<connected-to-ad1939_mclk_clk>),                        //                       ad1939_mclk.clk
		.mclk_pll_locked_export                 (<connected-to-mclk_pll_locked_export>),                 //                   mclk_pll_locked.export
		.addr_sel_in_add_sel                    (<connected-to-addr_sel_in_add_sel>),                    //                       addr_sel_in.add_sel
		.emif_0_pll_extra_clk_0_pll_extra_clk_0 (<connected-to-emif_0_pll_extra_clk_0_pll_extra_clk_0>), //            emif_0_pll_extra_clk_0.pll_extra_clk_0
		.mm_clock_crossing_bridge_0_s0_clk_clk  (<connected-to-mm_clock_crossing_bridge_0_s0_clk_clk>),  // mm_clock_crossing_bridge_0_s0_clk.clk
		.arria10_hps_0_h2f_axi_clock_clk        (<connected-to-arria10_hps_0_h2f_axi_clock_clk>),        //       arria10_hps_0_h2f_axi_clock.clk
		.emif_0_status_local_cal_success        (<connected-to-emif_0_status_local_cal_success>),        //                     emif_0_status.local_cal_success
		.emif_0_status_local_cal_fail           (<connected-to-emif_0_status_local_cal_fail>),           //                                  .local_cal_fail
		.emif_0_mem_mem_ck                      (<connected-to-emif_0_mem_mem_ck>),                      //                        emif_0_mem.mem_ck
		.emif_0_mem_mem_ck_n                    (<connected-to-emif_0_mem_mem_ck_n>),                    //                                  .mem_ck_n
		.emif_0_mem_mem_a                       (<connected-to-emif_0_mem_mem_a>),                       //                                  .mem_a
		.emif_0_mem_mem_act_n                   (<connected-to-emif_0_mem_mem_act_n>),                   //                                  .mem_act_n
		.emif_0_mem_mem_ba                      (<connected-to-emif_0_mem_mem_ba>),                      //                                  .mem_ba
		.emif_0_mem_mem_bg                      (<connected-to-emif_0_mem_mem_bg>),                      //                                  .mem_bg
		.emif_0_mem_mem_cke                     (<connected-to-emif_0_mem_mem_cke>),                     //                                  .mem_cke
		.emif_0_mem_mem_cs_n                    (<connected-to-emif_0_mem_mem_cs_n>),                    //                                  .mem_cs_n
		.emif_0_mem_mem_odt                     (<connected-to-emif_0_mem_mem_odt>),                     //                                  .mem_odt
		.emif_0_mem_mem_reset_n                 (<connected-to-emif_0_mem_mem_reset_n>),                 //                                  .mem_reset_n
		.emif_0_mem_mem_par                     (<connected-to-emif_0_mem_mem_par>),                     //                                  .mem_par
		.emif_0_mem_mem_alert_n                 (<connected-to-emif_0_mem_mem_alert_n>),                 //                                  .mem_alert_n
		.emif_0_mem_mem_dqs                     (<connected-to-emif_0_mem_mem_dqs>),                     //                                  .mem_dqs
		.emif_0_mem_mem_dqs_n                   (<connected-to-emif_0_mem_mem_dqs_n>),                   //                                  .mem_dqs_n
		.emif_0_mem_mem_dq                      (<connected-to-emif_0_mem_mem_dq>),                      //                                  .mem_dq
		.emif_0_mem_mem_dbi_n                   (<connected-to-emif_0_mem_mem_dbi_n>),                   //                                  .mem_dbi_n
		.emif_0_oct_oct_rzqin                   (<connected-to-emif_0_oct_oct_rzqin>),                   //                        emif_0_oct.oct_rzqin
		.emif_0_global_reset_n_reset_n          (<connected-to-emif_0_global_reset_n_reset_n>),          //             emif_0_global_reset_n.reset_n
		.emif_0_pll_ref_clk_clk                 (<connected-to-emif_0_pll_ref_clk_clk>),                 //                emif_0_pll_ref_clk.clk
		.emif_0_pll_locked_pll_locked           (<connected-to-emif_0_pll_locked_pll_locked>)            //                 emif_0_pll_locked.pll_locked
	);

