-- soc_system_mic_array_clocks_10_hjvfn7a.vhd

-- Generated using ACDS version 18.0 614

library IEEE;
library soc_system_altera_iopll_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use soc_system_altera_iopll_180.soc_system_mic_array_clocks_10_hjvfn7a_pkg.all;

entity soc_system_mic_array_clocks_10_hjvfn7a is
	port (
		ad1939_mclk_clk       : in  std_logic := '0'; --       ad1939_mclk.clk
		reset_reset_n         : in  std_logic := '0'; --             reset.reset_n
		sck_master_clk        : out std_logic;        --        sck_master.clk
		sck_master_export_clk : out std_logic;        -- sck_master_export.clk
		sck_rcv_ch0_clk       : out std_logic         --       sck_rcv_ch0.clk
	);
end entity soc_system_mic_array_clocks_10_hjvfn7a;

architecture rtl of soc_system_mic_array_clocks_10_hjvfn7a is
	signal sck_pll_outclk0_clk     : std_logic; -- sck_pll:outclk_0 -> [sck_master_clk, sck_master_export_clk]
	signal reset_reset_n_ports_inv : std_logic; -- reset_reset_n:inv -> sck_pll:rst

begin

	sck_pll : component soc_system_altera_iopll_180.soc_system_mic_array_clocks_10_hjvfn7a_pkg.soc_system_altera_iopll_180_qn6opli
		port map (
			rst      => reset_reset_n_ports_inv, --   reset.reset
			refclk   => ad1939_mclk_clk,         --  refclk.clk
			outclk_0 => sck_pll_outclk0_clk,     -- outclk0.clk
			outclk_1 => sck_rcv_ch0_clk          -- outclk1.clk
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

	sck_master_clk <= sck_pll_outclk0_clk;

	sck_master_export_clk <= sck_pll_outclk0_clk;

end architecture rtl; -- of soc_system_mic_array_clocks_10_hjvfn7a
