	som_system u0 (
		.ad1939_abclk_clk                               (<connected-to-ad1939_abclk_clk>),                               //                           ad1939_abclk.clk
		.ad1939_alrclk_clk                              (<connected-to-ad1939_alrclk_clk>),                              //                          ad1939_alrclk.clk
		.ad1939_mclk_clk                                (<connected-to-ad1939_mclk_clk>),                                //                            ad1939_mclk.clk
		.ad1939_physical_ad1939_adc_asdata1             (<connected-to-ad1939_physical_ad1939_adc_asdata1>),             //                        ad1939_physical.ad1939_adc_asdata1
		.ad1939_physical_ad1939_adc_asdata2             (<connected-to-ad1939_physical_ad1939_adc_asdata2>),             //                                       .ad1939_adc_asdata2
		.ad1939_physical_ad1939_dac_dsdata1             (<connected-to-ad1939_physical_ad1939_dac_dsdata1>),             //                                       .ad1939_dac_dsdata1
		.ad1939_physical_ad1939_dac_dsdata2             (<connected-to-ad1939_physical_ad1939_dac_dsdata2>),             //                                       .ad1939_dac_dsdata2
		.ad1939_physical_ad1939_dac_dbclk               (<connected-to-ad1939_physical_ad1939_dac_dbclk>),               //                                       .ad1939_dac_dbclk
		.ad1939_physical_ad1939_dac_dlrclk              (<connected-to-ad1939_physical_ad1939_dac_dlrclk>),              //                                       .ad1939_dac_dlrclk
		.ad4020_left_physical_cnv                       (<connected-to-ad4020_left_physical_cnv>),                       //                   ad4020_left_physical.cnv
		.ad4020_left_physical_miso                      (<connected-to-ad4020_left_physical_miso>),                      //                                       .miso
		.ad4020_left_physical_mosi                      (<connected-to-ad4020_left_physical_mosi>),                      //                                       .mosi
		.ad4020_left_physical_sclk                      (<connected-to-ad4020_left_physical_sclk>),                      //                                       .sclk
		.ad4020_right_physical_cnv                      (<connected-to-ad4020_right_physical_cnv>),                      //                  ad4020_right_physical.cnv
		.ad4020_right_physical_miso                     (<connected-to-ad4020_right_physical_miso>),                     //                                       .miso
		.ad4020_right_physical_mosi                     (<connected-to-ad4020_right_physical_mosi>),                     //                                       .mosi
		.ad4020_right_physical_sclk                     (<connected-to-ad4020_right_physical_sclk>),                     //                                       .sclk
		.ad5791_left_physical_ad5791_clr_n_out          (<connected-to-ad5791_left_physical_ad5791_clr_n_out>),          //                   ad5791_left_physical.ad5791_clr_n_out
		.ad5791_left_physical_ad5791_ldac_n_out         (<connected-to-ad5791_left_physical_ad5791_ldac_n_out>),         //                                       .ad5791_ldac_n_out
		.ad5791_left_physical_ad5791_miso_out           (<connected-to-ad5791_left_physical_ad5791_miso_out>),           //                                       .ad5791_miso_out
		.ad5791_left_physical_ad5791_mosi_in            (<connected-to-ad5791_left_physical_ad5791_mosi_in>),            //                                       .ad5791_mosi_in
		.ad5791_left_physical_ad5791_sclk_out           (<connected-to-ad5791_left_physical_ad5791_sclk_out>),           //                                       .ad5791_sclk_out
		.ad5791_left_physical_ad5791_sync_n_out         (<connected-to-ad5791_left_physical_ad5791_sync_n_out>),         //                                       .ad5791_sync_n_out
		.ad5791_right_physical_ad5791_clr_n_out         (<connected-to-ad5791_right_physical_ad5791_clr_n_out>),         //                  ad5791_right_physical.ad5791_clr_n_out
		.ad5791_right_physical_ad5791_ldac_n_out        (<connected-to-ad5791_right_physical_ad5791_ldac_n_out>),        //                                       .ad5791_ldac_n_out
		.ad5791_right_physical_ad5791_miso_out          (<connected-to-ad5791_right_physical_ad5791_miso_out>),          //                                       .ad5791_miso_out
		.ad5791_right_physical_ad5791_mosi_in           (<connected-to-ad5791_right_physical_ad5791_mosi_in>),           //                                       .ad5791_mosi_in
		.ad5791_right_physical_ad5791_sclk_out          (<connected-to-ad5791_right_physical_ad5791_sclk_out>),          //                                       .ad5791_sclk_out
		.ad5791_right_physical_ad5791_sync_n_out        (<connected-to-ad5791_right_physical_ad5791_sync_n_out>),        //                                       .ad5791_sync_n_out
		.ad7768_physical_ad7768_dout_in                 (<connected-to-ad7768_physical_ad7768_dout_in>),                 //                        ad7768_physical.ad7768_dout_in
		.ad7768_physical_ad7768_drdy_in                 (<connected-to-ad7768_physical_ad7768_drdy_in>),                 //                                       .ad7768_drdy_in
		.ad7768_physical_ad7768_dclk_in                 (<connected-to-ad7768_physical_ad7768_dclk_in>),                 //                                       .ad7768_dclk_in
		.addr_sel_in_add_sel                            (<connected-to-addr_sel_in_add_sel>),                            //                            addr_sel_in.add_sel
		.axi_clk_bridge_in_clk_clk                      (<connected-to-axi_clk_bridge_in_clk_clk>),                      //                  axi_clk_bridge_in_clk.clk
		.clk_100_clk                                    (<connected-to-clk_100_clk>),                                    //                                clk_100.clk
		.ddr_ref_clk_clk                                (<connected-to-ddr_ref_clk_clk>),                                //                            ddr_ref_clk.clk
		.emif_0_global_reset_n_reset_n                  (<connected-to-emif_0_global_reset_n_reset_n>),                  //                  emif_0_global_reset_n.reset_n
		.emif_0_mem_mem_ck                              (<connected-to-emif_0_mem_mem_ck>),                              //                             emif_0_mem.mem_ck
		.emif_0_mem_mem_ck_n                            (<connected-to-emif_0_mem_mem_ck_n>),                            //                                       .mem_ck_n
		.emif_0_mem_mem_a                               (<connected-to-emif_0_mem_mem_a>),                               //                                       .mem_a
		.emif_0_mem_mem_act_n                           (<connected-to-emif_0_mem_mem_act_n>),                           //                                       .mem_act_n
		.emif_0_mem_mem_ba                              (<connected-to-emif_0_mem_mem_ba>),                              //                                       .mem_ba
		.emif_0_mem_mem_bg                              (<connected-to-emif_0_mem_mem_bg>),                              //                                       .mem_bg
		.emif_0_mem_mem_cke                             (<connected-to-emif_0_mem_mem_cke>),                             //                                       .mem_cke
		.emif_0_mem_mem_cs_n                            (<connected-to-emif_0_mem_mem_cs_n>),                            //                                       .mem_cs_n
		.emif_0_mem_mem_odt                             (<connected-to-emif_0_mem_mem_odt>),                             //                                       .mem_odt
		.emif_0_mem_mem_reset_n                         (<connected-to-emif_0_mem_mem_reset_n>),                         //                                       .mem_reset_n
		.emif_0_mem_mem_par                             (<connected-to-emif_0_mem_mem_par>),                             //                                       .mem_par
		.emif_0_mem_mem_alert_n                         (<connected-to-emif_0_mem_mem_alert_n>),                         //                                       .mem_alert_n
		.emif_0_mem_mem_dqs                             (<connected-to-emif_0_mem_mem_dqs>),                             //                                       .mem_dqs
		.emif_0_mem_mem_dqs_n                           (<connected-to-emif_0_mem_mem_dqs_n>),                           //                                       .mem_dqs_n
		.emif_0_mem_mem_dq                              (<connected-to-emif_0_mem_mem_dq>),                              //                                       .mem_dq
		.emif_0_mem_mem_dbi_n                           (<connected-to-emif_0_mem_mem_dbi_n>),                           //                                       .mem_dbi_n
		.emif_0_oct_oct_rzqin                           (<connected-to-emif_0_oct_oct_rzqin>),                           //                             emif_0_oct.oct_rzqin
		.emif_0_pll_extra_clk_0_pll_extra_clk_0         (<connected-to-emif_0_pll_extra_clk_0_pll_extra_clk_0>),         //                 emif_0_pll_extra_clk_0.pll_extra_clk_0
		.emif_0_pll_locked_pll_locked                   (<connected-to-emif_0_pll_locked_pll_locked>),                   //                      emif_0_pll_locked.pll_locked
		.emif_0_pll_ref_clk_clk                         (<connected-to-emif_0_pll_ref_clk_clk>),                         //                     emif_0_pll_ref_clk.clk
		.emif_0_status_local_cal_success                (<connected-to-emif_0_status_local_cal_success>),                //                          emif_0_status.local_cal_success
		.emif_0_status_local_cal_fail                   (<connected-to-emif_0_status_local_cal_fail>),                   //                                       .local_cal_fail
		.emif_a10_hps_0_global_reset_reset_sink_reset_n (<connected-to-emif_a10_hps_0_global_reset_reset_sink_reset_n>), // emif_a10_hps_0_global_reset_reset_sink.reset_n
		.hps_0_h2f_reset_reset_n                        (<connected-to-hps_0_h2f_reset_reset_n>),                        //                        hps_0_h2f_reset.reset_n
		.hps_io_hps_io_gpio_gpio2_io6                   (<connected-to-hps_io_hps_io_gpio_gpio2_io6>),                   //                                 hps_io.hps_io_gpio_gpio2_io6
		.hps_io_hps_io_gpio_gpio2_io8                   (<connected-to-hps_io_hps_io_gpio_gpio2_io8>),                   //                                       .hps_io_gpio_gpio2_io8
		.hps_io_hps_io_gpio_gpio0_io6                   (<connected-to-hps_io_hps_io_gpio_gpio0_io6>),                   //                                       .hps_io_gpio_gpio0_io6
		.hps_io_hps_io_gpio_gpio0_io11                  (<connected-to-hps_io_hps_io_gpio_gpio0_io11>),                  //                                       .hps_io_gpio_gpio0_io11
		.hps_io_hps_io_gpio_gpio1_io12                  (<connected-to-hps_io_hps_io_gpio_gpio1_io12>),                  //                                       .hps_io_gpio_gpio1_io12
		.hps_io_hps_io_gpio_gpio1_io13                  (<connected-to-hps_io_hps_io_gpio_gpio1_io13>),                  //                                       .hps_io_gpio_gpio1_io13
		.hps_io_hps_io_gpio_gpio1_io14                  (<connected-to-hps_io_hps_io_gpio_gpio1_io14>),                  //                                       .hps_io_gpio_gpio1_io14
		.hps_io_hps_io_gpio_gpio1_io15                  (<connected-to-hps_io_hps_io_gpio_gpio1_io15>),                  //                                       .hps_io_gpio_gpio1_io15
		.hps_io_hps_io_gpio_gpio1_io16                  (<connected-to-hps_io_hps_io_gpio_gpio1_io16>),                  //                                       .hps_io_gpio_gpio1_io16
		.hps_io_hps_io_gpio_gpio1_io17                  (<connected-to-hps_io_hps_io_gpio_gpio1_io17>),                  //                                       .hps_io_gpio_gpio1_io17
		.hps_io_hps_io_gpio_gpio1_io18                  (<connected-to-hps_io_hps_io_gpio_gpio1_io18>),                  //                                       .hps_io_gpio_gpio1_io18
		.hps_io_hps_io_gpio_gpio1_io19                  (<connected-to-hps_io_hps_io_gpio_gpio1_io19>),                  //                                       .hps_io_gpio_gpio1_io19
		.hps_io_hps_io_gpio_gpio1_io20                  (<connected-to-hps_io_hps_io_gpio_gpio1_io20>),                  //                                       .hps_io_gpio_gpio1_io20
		.hps_io_hps_io_gpio_gpio1_io21                  (<connected-to-hps_io_hps_io_gpio_gpio1_io21>),                  //                                       .hps_io_gpio_gpio1_io21
		.hps_io_hps_io_gpio_gpio1_io22                  (<connected-to-hps_io_hps_io_gpio_gpio1_io22>),                  //                                       .hps_io_gpio_gpio1_io22
		.hps_io_hps_io_gpio_gpio1_io23                  (<connected-to-hps_io_hps_io_gpio_gpio1_io23>),                  //                                       .hps_io_gpio_gpio1_io23
		.hps_spim0_mosi_o                               (<connected-to-hps_spim0_mosi_o>),                               //                              hps_spim0.mosi_o
		.hps_spim0_miso_i                               (<connected-to-hps_spim0_miso_i>),                               //                                       .miso_i
		.hps_spim0_ss_in_n                              (<connected-to-hps_spim0_ss_in_n>),                              //                                       .ss_in_n
		.hps_spim0_mosi_oe                              (<connected-to-hps_spim0_mosi_oe>),                              //                                       .mosi_oe
		.hps_spim0_ss0_n_o                              (<connected-to-hps_spim0_ss0_n_o>),                              //                                       .ss0_n_o
		.hps_spim0_ss1_n_o                              (<connected-to-hps_spim0_ss1_n_o>),                              //                                       .ss1_n_o
		.hps_spim0_ss2_n_o                              (<connected-to-hps_spim0_ss2_n_o>),                              //                                       .ss2_n_o
		.hps_spim0_ss3_n_o                              (<connected-to-hps_spim0_ss3_n_o>),                              //                                       .ss3_n_o
		.hps_spim0_sclk_out_clk                         (<connected-to-hps_spim0_sclk_out_clk>),                         //                     hps_spim0_sclk_out.clk
		.mclk_pll_locked_export                         (<connected-to-mclk_pll_locked_export>),                         //                        mclk_pll_locked.export
		.mem_mem_ck                                     (<connected-to-mem_mem_ck>),                                     //                                    mem.mem_ck
		.mem_mem_ck_n                                   (<connected-to-mem_mem_ck_n>),                                   //                                       .mem_ck_n
		.mem_mem_a                                      (<connected-to-mem_mem_a>),                                      //                                       .mem_a
		.mem_mem_act_n                                  (<connected-to-mem_mem_act_n>),                                  //                                       .mem_act_n
		.mem_mem_ba                                     (<connected-to-mem_mem_ba>),                                     //                                       .mem_ba
		.mem_mem_bg                                     (<connected-to-mem_mem_bg>),                                     //                                       .mem_bg
		.mem_mem_cke                                    (<connected-to-mem_mem_cke>),                                    //                                       .mem_cke
		.mem_mem_cs_n                                   (<connected-to-mem_mem_cs_n>),                                   //                                       .mem_cs_n
		.mem_mem_odt                                    (<connected-to-mem_mem_odt>),                                    //                                       .mem_odt
		.mem_mem_reset_n                                (<connected-to-mem_mem_reset_n>),                                //                                       .mem_reset_n
		.mem_mem_par                                    (<connected-to-mem_mem_par>),                                    //                                       .mem_par
		.mem_mem_alert_n                                (<connected-to-mem_mem_alert_n>),                                //                                       .mem_alert_n
		.mem_mem_dqs                                    (<connected-to-mem_mem_dqs>),                                    //                                       .mem_dqs
		.mem_mem_dqs_n                                  (<connected-to-mem_mem_dqs_n>),                                  //                                       .mem_dqs_n
		.mem_mem_dq                                     (<connected-to-mem_mem_dq>),                                     //                                       .mem_dq
		.mem_mem_dbi_n                                  (<connected-to-mem_mem_dbi_n>),                                  //                                       .mem_dbi_n
		.mic_array0_control_busy_out                    (<connected-to-mic_array0_control_busy_out>),                    //                     mic_array0_control.busy_out
		.mic_array0_physical_serial_data_in             (<connected-to-mic_array0_physical_serial_data_in>),             //                    mic_array0_physical.serial_data_in
		.mic_array0_physical_serial_data_out            (<connected-to-mic_array0_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array0_physical_serial_clk_out             (<connected-to-mic_array0_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array10_control_busy_out                   (<connected-to-mic_array10_control_busy_out>),                   //                    mic_array10_control.busy_out
		.mic_array10_physical_serial_data_in            (<connected-to-mic_array10_physical_serial_data_in>),            //                   mic_array10_physical.serial_data_in
		.mic_array10_physical_serial_data_out           (<connected-to-mic_array10_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array10_physical_serial_clk_out            (<connected-to-mic_array10_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array11_control_busy_out                   (<connected-to-mic_array11_control_busy_out>),                   //                    mic_array11_control.busy_out
		.mic_array11_physical_serial_data_in            (<connected-to-mic_array11_physical_serial_data_in>),            //                   mic_array11_physical.serial_data_in
		.mic_array11_physical_serial_data_out           (<connected-to-mic_array11_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array11_physical_serial_clk_out            (<connected-to-mic_array11_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array12_control_busy_out                   (<connected-to-mic_array12_control_busy_out>),                   //                    mic_array12_control.busy_out
		.mic_array12_physical_serial_data_in            (<connected-to-mic_array12_physical_serial_data_in>),            //                   mic_array12_physical.serial_data_in
		.mic_array12_physical_serial_data_out           (<connected-to-mic_array12_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array12_physical_serial_clk_out            (<connected-to-mic_array12_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array13_control_busy_out                   (<connected-to-mic_array13_control_busy_out>),                   //                    mic_array13_control.busy_out
		.mic_array13_physical_serial_data_in            (<connected-to-mic_array13_physical_serial_data_in>),            //                   mic_array13_physical.serial_data_in
		.mic_array13_physical_serial_data_out           (<connected-to-mic_array13_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array13_physical_serial_clk_out            (<connected-to-mic_array13_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array14_control_busy_out                   (<connected-to-mic_array14_control_busy_out>),                   //                    mic_array14_control.busy_out
		.mic_array14_physical_serial_data_in            (<connected-to-mic_array14_physical_serial_data_in>),            //                   mic_array14_physical.serial_data_in
		.mic_array14_physical_serial_data_out           (<connected-to-mic_array14_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array14_physical_serial_clk_out            (<connected-to-mic_array14_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array15_control_busy_out                   (<connected-to-mic_array15_control_busy_out>),                   //                    mic_array15_control.busy_out
		.mic_array15_physical_serial_data_in            (<connected-to-mic_array15_physical_serial_data_in>),            //                   mic_array15_physical.serial_data_in
		.mic_array15_physical_serial_data_out           (<connected-to-mic_array15_physical_serial_data_out>),           //                                       .serial_data_out
		.mic_array15_physical_serial_clk_out            (<connected-to-mic_array15_physical_serial_clk_out>),            //                                       .serial_clk_out
		.mic_array1_control_busy_out                    (<connected-to-mic_array1_control_busy_out>),                    //                     mic_array1_control.busy_out
		.mic_array1_physical_serial_data_in             (<connected-to-mic_array1_physical_serial_data_in>),             //                    mic_array1_physical.serial_data_in
		.mic_array1_physical_serial_data_out            (<connected-to-mic_array1_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array1_physical_serial_clk_out             (<connected-to-mic_array1_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array2_control_busy_out                    (<connected-to-mic_array2_control_busy_out>),                    //                     mic_array2_control.busy_out
		.mic_array2_physical_serial_data_in             (<connected-to-mic_array2_physical_serial_data_in>),             //                    mic_array2_physical.serial_data_in
		.mic_array2_physical_serial_data_out            (<connected-to-mic_array2_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array2_physical_serial_clk_out             (<connected-to-mic_array2_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array3_control_busy_out                    (<connected-to-mic_array3_control_busy_out>),                    //                     mic_array3_control.busy_out
		.mic_array3_physical_serial_data_in             (<connected-to-mic_array3_physical_serial_data_in>),             //                    mic_array3_physical.serial_data_in
		.mic_array3_physical_serial_data_out            (<connected-to-mic_array3_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array3_physical_serial_clk_out             (<connected-to-mic_array3_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array4_control_busy_out                    (<connected-to-mic_array4_control_busy_out>),                    //                     mic_array4_control.busy_out
		.mic_array4_physical_serial_data_in             (<connected-to-mic_array4_physical_serial_data_in>),             //                    mic_array4_physical.serial_data_in
		.mic_array4_physical_serial_data_out            (<connected-to-mic_array4_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array4_physical_serial_clk_out             (<connected-to-mic_array4_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array5_control_busy_out                    (<connected-to-mic_array5_control_busy_out>),                    //                     mic_array5_control.busy_out
		.mic_array5_physical_serial_data_in             (<connected-to-mic_array5_physical_serial_data_in>),             //                    mic_array5_physical.serial_data_in
		.mic_array5_physical_serial_data_out            (<connected-to-mic_array5_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array5_physical_serial_clk_out             (<connected-to-mic_array5_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array6_physical_serial_data_in             (<connected-to-mic_array6_physical_serial_data_in>),             //                    mic_array6_physical.serial_data_in
		.mic_array6_physical_serial_data_out            (<connected-to-mic_array6_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array6_physical_serial_clk_out             (<connected-to-mic_array6_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array6_physical_1_busy_out                 (<connected-to-mic_array6_physical_1_busy_out>),                 //                  mic_array6_physical_1.busy_out
		.mic_array7_control_busy_out                    (<connected-to-mic_array7_control_busy_out>),                    //                     mic_array7_control.busy_out
		.mic_array7_physical_serial_data_in             (<connected-to-mic_array7_physical_serial_data_in>),             //                    mic_array7_physical.serial_data_in
		.mic_array7_physical_serial_data_out            (<connected-to-mic_array7_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array7_physical_serial_clk_out             (<connected-to-mic_array7_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array8_control_busy_out                    (<connected-to-mic_array8_control_busy_out>),                    //                     mic_array8_control.busy_out
		.mic_array8_physical_serial_data_in             (<connected-to-mic_array8_physical_serial_data_in>),             //                    mic_array8_physical.serial_data_in
		.mic_array8_physical_serial_data_out            (<connected-to-mic_array8_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array8_physical_serial_clk_out             (<connected-to-mic_array8_physical_serial_clk_out>),             //                                       .serial_clk_out
		.mic_array9_control_busy_out                    (<connected-to-mic_array9_control_busy_out>),                    //                     mic_array9_control.busy_out
		.mic_array9_physical_serial_data_in             (<connected-to-mic_array9_physical_serial_data_in>),             //                    mic_array9_physical.serial_data_in
		.mic_array9_physical_serial_data_out            (<connected-to-mic_array9_physical_serial_data_out>),            //                                       .serial_data_out
		.mic_array9_physical_serial_clk_out             (<connected-to-mic_array9_physical_serial_clk_out>),             //                                       .serial_clk_out
		.oct_oct_rzqin                                  (<connected-to-oct_oct_rzqin>),                                  //                                    oct.oct_rzqin
		.reset_reset_n                                  (<connected-to-reset_reset_n>),                                  //                                  reset.reset_n
		.som_config_pio_export                          (<connected-to-som_config_pio_export>),                          //                         som_config_pio.export
		.hps_i2c1_scl_in_clk                            (<connected-to-hps_i2c1_scl_in_clk>),                            //                        hps_i2c1_scl_in.clk
		.hps_i2c1_clk_clk                               (<connected-to-hps_i2c1_clk_clk>),                               //                           hps_i2c1_clk.clk
		.hps_i2c1_sda_i                                 (<connected-to-hps_i2c1_sda_i>),                                 //                               hps_i2c1.sda_i
		.hps_i2c1_sda_oe                                (<connected-to-hps_i2c1_sda_oe>)                                 //                                       .sda_oe
	);

