SLStudio.Utils.RemoveHighlighting(get_param('DSBF', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_DSBF', 'handle'));
annotate_port('gm_DSBF/dataplane/Avalon Data Processing', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/Delay2', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/Delay2', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/Delay3', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/Delay3', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator1', 0, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator1', 0, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator', 0, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator', 0, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Rate Transition', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Rate Transition', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Downsample', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Downsample', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 1, 1, '');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/CIC Interpolation', 1, 1, '');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 1, 1, '');
