open_system('DSBF');
open_system('gm_DSBF');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('DSBF/dataplane/Avalon Data Processing', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/Delay2', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/Delay2', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/Delay2', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/Delay3', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/Delay3', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/Delay3', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal', 1, 1, 'This subsystem is inhibiting clock-rate pipelining.');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator1', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator1', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator1', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator1', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/write address generator', 0, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/write address generator', 0, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Rate Transition', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Rate Transition', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Rate Transition', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Rate Transition', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Downsample', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/Downsample', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Downsample', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/Downsample', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 1, 1, 'Obstacle to clock-rate pipelining');
cs.HiliteType = 'user2';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'gray';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/CIC Interpolation', 'user2');
annotate_port('gm_DSBF/dataplane/Avalon Data Processing/delay signals_instance1/delay signal/CIC Interpolation', 1, 1, 'Obstacle to clock-rate pipelining');
hilite_system('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 'user2');
annotate_port('DSBF/dataplane/Avalon Data Processing/delay signals/delay signal/CIC Interpolation', 1, 1, 'Obstacle to clock-rate pipelining');
