config soc_system_altera_mm_interconnect_180_h4iigbi_cfg;
		design soc_system_altera_mm_interconnect_180_h4iigbi;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.sysid_qsys_0_control_slave_translator use soc_system_altera_merlin_slave_translator_180.altera_merlin_slave_translator;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.hps_h2f_lw_axi_master_agent use soc_system_altera_merlin_axi_master_ni_180.altera_merlin_axi_master_ni;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.sysid_qsys_0_control_slave_agent use soc_system_altera_merlin_slave_agent_180.altera_merlin_slave_agent;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.sysid_qsys_0_control_slave_agent_rsp_fifo use soc_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.sysid_qsys_0_control_slave_agent_rdata_fifo use soc_system_altera_avalon_sc_fifo_180.altera_avalon_sc_fifo;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.router use soc_system_altera_merlin_router_180.soc_system_altera_merlin_router_180_ok3a5xq;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.router_001 use soc_system_altera_merlin_router_180.soc_system_altera_merlin_router_180_ok3a5xq;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.router_002 use soc_system_altera_merlin_router_180.soc_system_altera_merlin_router_180_6yqffvy;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.sysid_qsys_0_control_slave_burst_adapter use soc_system_altera_merlin_burst_adapter_180.altera_merlin_burst_adapter;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.cmd_demux use soc_system_altera_merlin_demultiplexer_180.soc_system_altera_merlin_demultiplexer_180_7vxr2oy;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.cmd_demux_001 use soc_system_altera_merlin_demultiplexer_180.soc_system_altera_merlin_demultiplexer_180_7vxr2oy;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.cmd_mux use soc_system_altera_merlin_multiplexer_180.soc_system_altera_merlin_multiplexer_180_aogbhry;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.rsp_demux use soc_system_altera_merlin_demultiplexer_180.soc_system_altera_merlin_demultiplexer_180_ryto4cq;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.rsp_mux use soc_system_altera_merlin_multiplexer_180.soc_system_altera_merlin_multiplexer_180_27h65fa;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.rsp_mux_001 use soc_system_altera_merlin_multiplexer_180.soc_system_altera_merlin_multiplexer_180_27h65fa;
		instance soc_system_altera_mm_interconnect_180_h4iigbi.avalon_st_adapter use soc_system_altera_avalon_st_adapter_180.soc_system_altera_avalon_st_adapter_180_7g3x3ri;
endconfig

