config soc_system_altera_arria10_hps_180_ruxeq2a_cfg;
		design soc_system_altera_arria10_hps_180_ruxeq2a;
		instance soc_system_altera_arria10_hps_180_ruxeq2a.fpga_interfaces use soc_system_altera_arria10_interface_generator_140.soc_system_altera_arria10_interface_generator_140_vbjqidy;
		instance soc_system_altera_arria10_hps_180_ruxeq2a.hps_io use soc_system_altera_arria10_hps_io_180.soc_system_altera_arria10_hps_io_180_geofrnq;
endconfig

