config som_system_altera_arria10_hps_io_180_6ukphhy_cfg;
		design som_system_altera_arria10_hps_io_180_6ukphhy;
		instance som_system_altera_arria10_hps_io_180_6ukphhy.border use som_system_altera_arria10_interface_generator_140.som_system_altera_arria10_interface_generator_140_mv5mwwi;
endconfig

