config som_system_altera_arria10_hps_180_zmlrihi_cfg;
		design som_system_altera_arria10_hps_180_zmlrihi;
		instance som_system_altera_arria10_hps_180_zmlrihi.fpga_interfaces use som_system_altera_arria10_interface_generator_140.som_system_altera_arria10_interface_generator_140_hnufizi;
		instance som_system_altera_arria10_hps_180_zmlrihi.hps_io use som_system_altera_arria10_hps_io_180.som_system_altera_arria10_hps_io_180_of6hmti;
endconfig

