config soc_system_altera_avalon_st_adapter_180_xlz2poi_cfg;
		design soc_system_altera_avalon_st_adapter_180_xlz2poi;
		instance soc_system_altera_avalon_st_adapter_180_xlz2poi.channel_adapter_0 use soc_system_channel_adapter_180.soc_system_channel_adapter_180_zwdd44y;
endconfig

