config soc_system_altera_avalon_st_adapter_180_g7t4xhq_cfg;
		design soc_system_altera_avalon_st_adapter_180_g7t4xhq;
		instance soc_system_altera_avalon_st_adapter_180_g7t4xhq.channel_adapter_0 use soc_system_channel_adapter_180.soc_system_channel_adapter_180_76u3bzq;
		instance soc_system_altera_avalon_st_adapter_180_g7t4xhq.error_adapter_0 use soc_system_error_adapter_180.soc_system_error_adapter_180_2gnarnq;
endconfig

