config soc_system_altera_avalon_st_adapter_180_6zobqby_cfg;
		design soc_system_altera_avalon_st_adapter_180_6zobqby;
		instance soc_system_altera_avalon_st_adapter_180_6zobqby.channel_adapter_0 use soc_system_channel_adapter_180.soc_system_channel_adapter_180_3ybmbmq;
endconfig

